package types

import "cosmossdk.io/errors"

var (
	ErrChainNotSupported            = errors.Register(ModuleName, 2, "chain not supported")
	ErrChainPaused                  = errors.Register(ModuleName, 3, "bridge for chain is paused")
	ErrInvalidAttestation           = errors.Register(ModuleName, 4, "invalid bridge attestation")
	ErrDuplicateAttestation         = errors.Register(ModuleName, 5, "duplicate attestation")
	ErrInsufficientAttestations     = errors.Register(ModuleName, 6, "insufficient attestations for threshold")
	ErrValidatorNotRegistered       = errors.Register(ModuleName, 7, "validator not registered as bridge validator")
	ErrValidatorNotAuthorized       = errors.Register(ModuleName, 8, "validator not authorized for this chain")
	ErrExceedsSingleTransferLimit   = errors.Register(ModuleName, 9, "transfer exceeds single transfer limit")
	ErrExceedsDailyLimit            = errors.Register(ModuleName, 10, "transfer exceeds daily limit")
	ErrBridgePaused                 = errors.Register(ModuleName, 11, "bridge is paused")
	ErrInvalidPQCSignature          = errors.Register(ModuleName, 12, "invalid PQC signature on attestation")
	ErrOperationNotFound            = errors.Register(ModuleName, 13, "bridge operation not found")
	ErrOperationAlreadyCompleted    = errors.Register(ModuleName, 14, "bridge operation already completed")
	ErrInvalidAmount                = errors.Register(ModuleName, 15, "invalid bridge amount")
	ErrAssetNotSupported            = errors.Register(ModuleName, 16, "asset not supported on this chain")
	ErrInvalidDestination           = errors.Register(ModuleName, 17, "invalid destination address")
	ErrChallengePeriodActive        = errors.Register(ModuleName, 18, "challenge period still active")
	ErrUnauthorizedAttestor         = errors.Register(ModuleName, 19, "attestor pubkey not registered as bridge validator")
	ErrOperationExecuting           = errors.Register(ModuleName, 20, "operation is currently executing")
	ErrInvalidDepositProof          = errors.Register(ModuleName, 21, "invalid deposit proof")
	ErrOperationMaxRetries          = errors.Register(ModuleName, 22, "operation exhausted maximum retries")
	ErrMintFailed                   = errors.Register(ModuleName, 23, "failed to mint bridged tokens")
	ErrCircuitBreakerResetFailed    = errors.Register(ModuleName, 24, "failed to persist circuit breaker reset")
	ErrInsufficientBalance          = errors.Register(ModuleName, 25, "insufficient bridged token balance")
	ErrTooManyAttestations          = errors.Register(ModuleName, 26, "too many attestations for operation")
	ErrDuplicateOperation           = errors.Register(ModuleName, 27, "duplicate source transaction hash")
	ErrUnauthorized                 = errors.Register(ModuleName, 28, "unauthorized bridge operation")
	ErrDepositVerifierNotConfigured = errors.Register(ModuleName, 29, "deposit verifier not configured")
	ErrEventTypeMismatch            = errors.Register(ModuleName, 30, "attestation event type does not match operation type")
)
