// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/ai/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ConfigView struct {
	AnomalyThreshold string `protobuf:"bytes,1,opt,name=anomaly_threshold,json=anomalyThreshold,proto3" json:"anomaly_threshold,omitempty"`
	RoutingStrategy  string `protobuf:"bytes,2,opt,name=routing_strategy,json=routingStrategy,proto3" json:"routing_strategy,omitempty"`
	RiskThreshold    string `protobuf:"bytes,3,opt,name=risk_threshold,json=riskThreshold,proto3" json:"risk_threshold,omitempty"`
	MaxTxPerMinute   int32  `protobuf:"varint,4,opt,name=max_tx_per_minute,json=maxTxPerMinute,proto3" json:"max_tx_per_minute,omitempty"`
}

func (m *ConfigView) Reset()         { *m = ConfigView{} }
func (m *ConfigView) String() string { return proto.CompactTextString(m) }
func (*ConfigView) ProtoMessage()    {}
func (*ConfigView) Descriptor() ([]byte, []int) {
	return fileDescriptor_383a16fc63e67a60, []int{0}
}
func (m *ConfigView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigView.Merge(m, src)
}
func (m *ConfigView) XXX_Size() int {
	return m.Size()
}
func (m *ConfigView) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigView.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigView proto.InternalMessageInfo

func (m *ConfigView) GetAnomalyThreshold() string {
	if m != nil {
		return m.AnomalyThreshold
	}
	return ""
}

func (m *ConfigView) GetRoutingStrategy() string {
	if m != nil {
		return m.RoutingStrategy
	}
	return ""
}

func (m *ConfigView) GetRiskThreshold() string {
	if m != nil {
		return m.RiskThreshold
	}
	return ""
}

func (m *ConfigView) GetMaxTxPerMinute() int32 {
	if m != nil {
		return m.MaxTxPerMinute
	}
	return 0
}

type StatsView struct {
	TxsRouted         uint64 `protobuf:"varint,1,opt,name=txs_routed,json=txsRouted,proto3" json:"txs_routed,omitempty"`
	AnomaliesDetected uint64 `protobuf:"varint,2,opt,name=anomalies_detected,json=anomaliesDetected,proto3" json:"anomalies_detected,omitempty"`
	ContractsScored   uint64 `protobuf:"varint,3,opt,name=contracts_scored,json=contractsScored,proto3" json:"contracts_scored,omitempty"`
	TxsFlagged        uint64 `protobuf:"varint,4,opt,name=txs_flagged,json=txsFlagged,proto3" json:"txs_flagged,omitempty"`
	TxsRejected       uint64 `protobuf:"varint,5,opt,name=txs_rejected,json=txsRejected,proto3" json:"txs_rejected,omitempty"`
}

func (m *StatsView) Reset()         { *m = StatsView{} }
func (m *StatsView) String() string { return proto.CompactTextString(m) }
func (*StatsView) ProtoMessage()    {}
func (*StatsView) Descriptor() ([]byte, []int) {
	return fileDescriptor_383a16fc63e67a60, []int{1}
}
func (m *StatsView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatsView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatsView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatsView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsView.Merge(m, src)
}
func (m *StatsView) XXX_Size() int {
	return m.Size()
}
func (m *StatsView) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsView.DiscardUnknown(m)
}

var xxx_messageInfo_StatsView proto.InternalMessageInfo

func (m *StatsView) GetTxsRouted() uint64 {
	if m != nil {
		return m.TxsRouted
	}
	return 0
}

func (m *StatsView) GetAnomaliesDetected() uint64 {
	if m != nil {
		return m.AnomaliesDetected
	}
	return 0
}

func (m *StatsView) GetContractsScored() uint64 {
	if m != nil {
		return m.ContractsScored
	}
	return 0
}

func (m *StatsView) GetTxsFlagged() uint64 {
	if m != nil {
		return m.TxsFlagged
	}
	return 0
}

func (m *StatsView) GetTxsRejected() uint64 {
	if m != nil {
		return m.TxsRejected
	}
	return 0
}

type QueryConfigRequest struct {
}

func (m *QueryConfigRequest) Reset()         { *m = QueryConfigRequest{} }
func (m *QueryConfigRequest) String() string { return proto.CompactTextString(m) }
func (*QueryConfigRequest) ProtoMessage()    {}
func (*QueryConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383a16fc63e67a60, []int{2}
}
func (m *QueryConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConfigRequest.Merge(m, src)
}
func (m *QueryConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConfigRequest proto.InternalMessageInfo

type QueryConfigResponse struct {
	Config *ConfigView `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *QueryConfigResponse) Reset()         { *m = QueryConfigResponse{} }
func (m *QueryConfigResponse) String() string { return proto.CompactTextString(m) }
func (*QueryConfigResponse) ProtoMessage()    {}
func (*QueryConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_383a16fc63e67a60, []int{3}
}
func (m *QueryConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConfigResponse.Merge(m, src)
}
func (m *QueryConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConfigResponse proto.InternalMessageInfo

func (m *QueryConfigResponse) GetConfig() *ConfigView {
	if m != nil {
		return m.Config
	}
	return nil
}

type QueryStatsRequest struct {
}

func (m *QueryStatsRequest) Reset()         { *m = QueryStatsRequest{} }
func (m *QueryStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStatsRequest) ProtoMessage()    {}
func (*QueryStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_383a16fc63e67a60, []int{4}
}
func (m *QueryStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsRequest.Merge(m, src)
}
func (m *QueryStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsRequest proto.InternalMessageInfo

type QueryStatsResponse struct {
	Stats *StatsView `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (m *QueryStatsResponse) Reset()         { *m = QueryStatsResponse{} }
func (m *QueryStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStatsResponse) ProtoMessage()    {}
func (*QueryStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_383a16fc63e67a60, []int{5}
}
func (m *QueryStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsResponse.Merge(m, src)
}
func (m *QueryStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsResponse proto.InternalMessageInfo

func (m *QueryStatsResponse) GetStats() *StatsView {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigView)(nil), "qorechain.ai.v1.ConfigView")
	proto.RegisterType((*StatsView)(nil), "qorechain.ai.v1.StatsView")
	proto.RegisterType((*QueryConfigRequest)(nil), "qorechain.ai.v1.QueryConfigRequest")
	proto.RegisterType((*QueryConfigResponse)(nil), "qorechain.ai.v1.QueryConfigResponse")
	proto.RegisterType((*QueryStatsRequest)(nil), "qorechain.ai.v1.QueryStatsRequest")
	proto.RegisterType((*QueryStatsResponse)(nil), "qorechain.ai.v1.QueryStatsResponse")
}

func init() { proto.RegisterFile("qorechain/ai/v1/query.proto", fileDescriptor_383a16fc63e67a60) }

var fileDescriptor_383a16fc63e67a60 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0xe3, 0xfe, 0x49, 0xa4, 0xdc, 0xfe, 0x34, 0xcd, 0x94, 0x45, 0x94, 0x0a, 0x53, 0x5c,
	0x90, 0x8a, 0x50, 0x6d, 0xda, 0xbe, 0x01, 0xa0, 0x0a, 0x21, 0x21, 0x95, 0x49, 0xc5, 0x82, 0x8d,
	0x35, 0x75, 0x6e, 0x9d, 0x81, 0xd8, 0x93, 0xcc, 0x8c, 0x8b, 0xf3, 0x16, 0x3c, 0x09, 0x4b, 0x9e,
	0xa1, 0xcb, 0x2e, 0x59, 0xa2, 0xe4, 0x45, 0xd0, 0x8c, 0xa7, 0x6e, 0x20, 0xa8, 0x3b, 0xeb, 0x9b,
	0xe3, 0x73, 0xce, 0x9d, 0xab, 0x81, 0xdd, 0x99, 0x90, 0x98, 0x8c, 0x19, 0xcf, 0x23, 0xc6, 0xa3,
	0xab, 0xa3, 0x68, 0x56, 0xa0, 0x9c, 0x87, 0x53, 0x29, 0xb4, 0x20, 0xdd, 0xfa, 0x30, 0x64, 0x3c,
	0xbc, 0x3a, 0x0a, 0x7e, 0x78, 0x00, 0xaf, 0x45, 0x7e, 0xc9, 0xd3, 0x8f, 0x1c, 0xbf, 0x92, 0x17,
	0xd0, 0x63, 0xb9, 0xc8, 0xd8, 0x64, 0x1e, 0xeb, 0xb1, 0x44, 0x35, 0x16, 0x93, 0x51, 0xdf, 0xdb,
	0xf3, 0x0e, 0x3a, 0x74, 0xdb, 0x1d, 0x9c, 0xdf, 0x72, 0xf2, 0x1c, 0xb6, 0xa5, 0x28, 0x34, 0xcf,
	0xd3, 0x58, 0x69, 0xc9, 0x34, 0xa6, 0xf3, 0xfe, 0x86, 0xd5, 0x76, 0x1d, 0x1f, 0x3a, 0x4c, 0x9e,
	0xc1, 0x96, 0xe4, 0xea, 0xcb, 0x8a, 0xe9, 0x7f, 0x56, 0xf8, 0xc0, 0xd0, 0x55, 0xc7, 0x5e, 0xc6,
	0xca, 0x58, 0x97, 0xf1, 0x14, 0x65, 0x9c, 0xf1, 0xbc, 0xd0, 0xd8, 0x6f, 0xee, 0x79, 0x07, 0x2d,
	0xba, 0x95, 0xb1, 0xf2, 0xbc, 0x3c, 0x43, 0xf9, 0xde, 0xd2, 0xe0, 0xda, 0x83, 0xce, 0x50, 0x33,
	0xad, 0x6c, 0xef, 0x47, 0x00, 0xba, 0x54, 0xb1, 0x89, 0xc5, 0xaa, 0x70, 0x93, 0x76, 0x74, 0xa9,
	0xa8, 0x05, 0xe4, 0x10, 0x48, 0xd5, 0x9e, 0xa3, 0x8a, 0x47, 0xa8, 0x31, 0x31, 0xb2, 0x0d, 0x2b,
	0xeb, 0xd5, 0x27, 0x6f, 0xdc, 0x81, 0x19, 0x2c, 0x11, 0xb9, 0x96, 0x2c, 0xd1, 0x2a, 0x56, 0x89,
	0x90, 0x58, 0xf5, 0x6d, 0xd2, 0x6e, 0xcd, 0x87, 0x16, 0x93, 0xc7, 0xb0, 0x69, 0x82, 0x2f, 0x27,
	0x2c, 0x4d, 0x71, 0x64, 0xbb, 0x36, 0xa9, 0xe9, 0x72, 0x5a, 0x11, 0xf2, 0x04, 0xfe, 0xb7, 0xcd,
	0xf0, 0x73, 0x15, 0xda, 0xb2, 0x0a, 0xf3, 0x13, 0x75, 0x28, 0x78, 0x08, 0xe4, 0x83, 0xd9, 0x51,
	0xb5, 0x07, 0x8a, 0xb3, 0x02, 0x95, 0x0e, 0xde, 0xc1, 0xce, 0x1f, 0x54, 0x4d, 0x45, 0xae, 0x90,
	0x9c, 0x40, 0x3b, 0xb1, 0xc4, 0x4e, 0xb9, 0x79, 0xbc, 0x1b, 0xfe, 0xb5, 0xd2, 0xf0, 0x6e, 0x9d,
	0xd4, 0x49, 0x83, 0x1d, 0xe8, 0x59, 0x2f, 0x7b, 0x61, 0xb7, 0x01, 0xa7, 0x2e, 0xd6, 0x41, 0xe7,
	0xff, 0x12, 0x5a, 0xca, 0x00, 0x67, 0x3f, 0x58, 0xb3, 0xaf, 0x2f, 0x9d, 0x56, 0xc2, 0xe3, 0xef,
	0x1e, 0xb4, 0xac, 0x11, 0x19, 0x42, 0xbb, 0x0a, 0x27, 0xfb, 0x6b, 0xbf, 0xad, 0x4f, 0x38, 0x78,
	0x7a, 0xbf, 0xc8, 0x15, 0x3a, 0x83, 0x96, 0x8d, 0x24, 0xc1, 0xbf, 0xe5, 0xab, 0x33, 0x0d, 0xf6,
	0xef, 0xd5, 0x54, 0x8e, 0xaf, 0xde, 0x5e, 0x2f, 0x7c, 0xef, 0x66, 0xe1, 0x7b, 0xbf, 0x16, 0xbe,
	0xf7, 0x6d, 0xe9, 0x37, 0x6e, 0x96, 0x7e, 0xe3, 0xe7, 0xd2, 0x6f, 0x7c, 0x0a, 0x53, 0xae, 0xc7,
	0xc5, 0x45, 0x98, 0x88, 0x2c, 0xba, 0x7b, 0x46, 0xf5, 0xd7, 0xa1, 0xd9, 0x79, 0x54, 0x9a, 0x77,
	0xa5, 0xe7, 0x53, 0x54, 0x17, 0x6d, 0xfb, 0xaa, 0x4e, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0x95, 0xa9, 0x07, 0x74, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Config returns the AI engine configuration.
	Config(ctx context.Context, in *QueryConfigRequest, opts ...grpc.CallOption) (*QueryConfigResponse, error)
	// Stats returns the AI engine runtime statistics.
	Stats(ctx context.Context, in *QueryStatsRequest, opts ...grpc.CallOption) (*QueryStatsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Config(ctx context.Context, in *QueryConfigRequest, opts ...grpc.CallOption) (*QueryConfigResponse, error) {
	out := new(QueryConfigResponse)
	err := c.cc.Invoke(ctx, "/qorechain.ai.v1.Query/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Stats(ctx context.Context, in *QueryStatsRequest, opts ...grpc.CallOption) (*QueryStatsResponse, error) {
	out := new(QueryStatsResponse)
	err := c.cc.Invoke(ctx, "/qorechain.ai.v1.Query/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Config returns the AI engine configuration.
	Config(context.Context, *QueryConfigRequest) (*QueryConfigResponse, error)
	// Stats returns the AI engine runtime statistics.
	Stats(context.Context, *QueryStatsRequest) (*QueryStatsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Config(ctx context.Context, req *QueryConfigRequest) (*QueryConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (*UnimplementedQueryServer) Stats(ctx context.Context, req *QueryStatsRequest) (*QueryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.ai.v1.Query/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Config(ctx, req.(*QueryConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.ai.v1.Query/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Stats(ctx, req.(*QueryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.ai.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _Query_Config_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Query_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/ai/v1/query.proto",
}

func (m *ConfigView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTxPerMinute != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxTxPerMinute))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RiskThreshold) > 0 {
		i -= len(m.RiskThreshold)
		copy(dAtA[i:], m.RiskThreshold)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RiskThreshold)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RoutingStrategy) > 0 {
		i -= len(m.RoutingStrategy)
		copy(dAtA[i:], m.RoutingStrategy)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RoutingStrategy)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AnomalyThreshold) > 0 {
		i -= len(m.AnomalyThreshold)
		copy(dAtA[i:], m.AnomalyThreshold)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AnomalyThreshold)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StatsView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatsView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatsView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxsRejected != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TxsRejected))
		i--
		dAtA[i] = 0x28
	}
	if m.TxsFlagged != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TxsFlagged))
		i--
		dAtA[i] = 0x20
	}
	if m.ContractsScored != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ContractsScored))
		i--
		dAtA[i] = 0x18
	}
	if m.AnomaliesDetected != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AnomaliesDetected))
		i--
		dAtA[i] = 0x10
	}
	if m.TxsRouted != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TxsRouted))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Config != nil {
		{
			size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stats != nil {
		{
			size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConfigView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AnomalyThreshold)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RoutingStrategy)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RiskThreshold)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.MaxTxPerMinute != 0 {
		n += 1 + sovQuery(uint64(m.MaxTxPerMinute))
	}
	return n
}

func (m *StatsView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxsRouted != 0 {
		n += 1 + sovQuery(uint64(m.TxsRouted))
	}
	if m.AnomaliesDetected != 0 {
		n += 1 + sovQuery(uint64(m.AnomaliesDetected))
	}
	if m.ContractsScored != 0 {
		n += 1 + sovQuery(uint64(m.ContractsScored))
	}
	if m.TxsFlagged != 0 {
		n += 1 + sovQuery(uint64(m.TxsFlagged))
	}
	if m.TxsRejected != 0 {
		n += 1 + sovQuery(uint64(m.TxsRejected))
	}
	return n
}

func (m *QueryConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stats != nil {
		l = m.Stats.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConfigView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnomalyThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnomalyThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingStrategy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoutingStrategy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RiskThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTxPerMinute", wireType)
			}
			m.MaxTxPerMinute = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTxPerMinute |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatsView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatsView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatsView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxsRouted", wireType)
			}
			m.TxsRouted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxsRouted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnomaliesDetected", wireType)
			}
			m.AnomaliesDetected = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AnomaliesDetected |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractsScored", wireType)
			}
			m.ContractsScored = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractsScored |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxsFlagged", wireType)
			}
			m.TxsFlagged = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxsFlagged |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxsRejected", wireType)
			}
			m.TxsRejected = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxsRejected |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &ConfigView{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stats == nil {
				m.Stats = &StatsView{}
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
