// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/rlconsensus/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAgentStatusRequest struct {
}

func (m *QueryAgentStatusRequest) Reset()         { *m = QueryAgentStatusRequest{} }
func (m *QueryAgentStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentStatusRequest) ProtoMessage()    {}
func (*QueryAgentStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1b919a53aee72c3, []int{0}
}
func (m *QueryAgentStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAgentStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAgentStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAgentStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentStatusRequest.Merge(m, src)
}
func (m *QueryAgentStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAgentStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentStatusRequest proto.InternalMessageInfo

type QueryAgentStatusResponse struct {
	Mode                 string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	CurrentEpoch         uint64 `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	TotalSteps           uint64 `protobuf:"varint,3,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	LastObservationAt    int64  `protobuf:"varint,4,opt,name=last_observation_at,json=lastObservationAt,proto3" json:"last_observation_at,omitempty"`
	LastActionAt         int64  `protobuf:"varint,5,opt,name=last_action_at,json=lastActionAt,proto3" json:"last_action_at,omitempty"`
	CircuitBreakerActive bool   `protobuf:"varint,6,opt,name=circuit_breaker_active,json=circuitBreakerActive,proto3" json:"circuit_breaker_active,omitempty"`
	BlocksSinceRevert    int64  `protobuf:"varint,7,opt,name=blocks_since_revert,json=blocksSinceRevert,proto3" json:"blocks_since_revert,omitempty"`
}

func (m *QueryAgentStatusResponse) Reset()         { *m = QueryAgentStatusResponse{} }
func (m *QueryAgentStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgentStatusResponse) ProtoMessage()    {}
func (*QueryAgentStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1b919a53aee72c3, []int{1}
}
func (m *QueryAgentStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAgentStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAgentStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAgentStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentStatusResponse.Merge(m, src)
}
func (m *QueryAgentStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAgentStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentStatusResponse proto.InternalMessageInfo

func (m *QueryAgentStatusResponse) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *QueryAgentStatusResponse) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *QueryAgentStatusResponse) GetTotalSteps() uint64 {
	if m != nil {
		return m.TotalSteps
	}
	return 0
}

func (m *QueryAgentStatusResponse) GetLastObservationAt() int64 {
	if m != nil {
		return m.LastObservationAt
	}
	return 0
}

func (m *QueryAgentStatusResponse) GetLastActionAt() int64 {
	if m != nil {
		return m.LastActionAt
	}
	return 0
}

func (m *QueryAgentStatusResponse) GetCircuitBreakerActive() bool {
	if m != nil {
		return m.CircuitBreakerActive
	}
	return false
}

func (m *QueryAgentStatusResponse) GetBlocksSinceRevert() int64 {
	if m != nil {
		return m.BlocksSinceRevert
	}
	return 0
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1b919a53aee72c3, []int{2}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Enabled                 bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ObservationInterval     uint64 `protobuf:"varint,2,opt,name=observation_interval,json=observationInterval,proto3" json:"observation_interval,omitempty"`
	AgentMode               string `protobuf:"bytes,3,opt,name=agent_mode,json=agentMode,proto3" json:"agent_mode,omitempty"`
	MaxChangeConservative   string `protobuf:"bytes,4,opt,name=max_change_conservative,json=maxChangeConservative,proto3" json:"max_change_conservative,omitempty"`
	MaxChangeAutonomous     string `protobuf:"bytes,5,opt,name=max_change_autonomous,json=maxChangeAutonomous,proto3" json:"max_change_autonomous,omitempty"`
	CircuitBreakerWindow    uint64 `protobuf:"varint,6,opt,name=circuit_breaker_window,json=circuitBreakerWindow,proto3" json:"circuit_breaker_window,omitempty"`
	CircuitBreakerThreshold string `protobuf:"bytes,7,opt,name=circuit_breaker_threshold,json=circuitBreakerThreshold,proto3" json:"circuit_breaker_threshold,omitempty"`
	// Reward weights (flattened to avoid clashing with the hand-written
	// types.RewardWeights struct used in genesis state).
	RewardWeightThroughput       string `protobuf:"bytes,8,opt,name=reward_weight_throughput,json=rewardWeightThroughput,proto3" json:"reward_weight_throughput,omitempty"`
	RewardWeightFinality         string `protobuf:"bytes,9,opt,name=reward_weight_finality,json=rewardWeightFinality,proto3" json:"reward_weight_finality,omitempty"`
	RewardWeightDecentralization string `protobuf:"bytes,10,opt,name=reward_weight_decentralization,json=rewardWeightDecentralization,proto3" json:"reward_weight_decentralization,omitempty"`
	RewardWeightMEV              string `protobuf:"bytes,11,opt,name=reward_weight_mev,json=rewardWeightMev,proto3" json:"reward_weight_mev,omitempty"`
	RewardWeightFailedTxs        string `protobuf:"bytes,12,opt,name=reward_weight_failed_txs,json=rewardWeightFailedTxs,proto3" json:"reward_weight_failed_txs,omitempty"`
	DefaultBlockTimeMs           int64  `protobuf:"varint,13,opt,name=default_block_time_ms,json=defaultBlockTimeMs,proto3" json:"default_block_time_ms,omitempty"`
	DefaultBaseGasPrice          string `protobuf:"bytes,14,opt,name=default_base_gas_price,json=defaultBaseGasPrice,proto3" json:"default_base_gas_price,omitempty"`
	DefaultValidatorSetSize      uint64 `protobuf:"varint,15,opt,name=default_validator_set_size,json=defaultValidatorSetSize,proto3" json:"default_validator_set_size,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1b919a53aee72c3, []int{3}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *QueryParamsResponse) GetObservationInterval() uint64 {
	if m != nil {
		return m.ObservationInterval
	}
	return 0
}

func (m *QueryParamsResponse) GetAgentMode() string {
	if m != nil {
		return m.AgentMode
	}
	return ""
}

func (m *QueryParamsResponse) GetMaxChangeConservative() string {
	if m != nil {
		return m.MaxChangeConservative
	}
	return ""
}

func (m *QueryParamsResponse) GetMaxChangeAutonomous() string {
	if m != nil {
		return m.MaxChangeAutonomous
	}
	return ""
}

func (m *QueryParamsResponse) GetCircuitBreakerWindow() uint64 {
	if m != nil {
		return m.CircuitBreakerWindow
	}
	return 0
}

func (m *QueryParamsResponse) GetCircuitBreakerThreshold() string {
	if m != nil {
		return m.CircuitBreakerThreshold
	}
	return ""
}

func (m *QueryParamsResponse) GetRewardWeightThroughput() string {
	if m != nil {
		return m.RewardWeightThroughput
	}
	return ""
}

func (m *QueryParamsResponse) GetRewardWeightFinality() string {
	if m != nil {
		return m.RewardWeightFinality
	}
	return ""
}

func (m *QueryParamsResponse) GetRewardWeightDecentralization() string {
	if m != nil {
		return m.RewardWeightDecentralization
	}
	return ""
}

func (m *QueryParamsResponse) GetRewardWeightMEV() string {
	if m != nil {
		return m.RewardWeightMEV
	}
	return ""
}

func (m *QueryParamsResponse) GetRewardWeightFailedTxs() string {
	if m != nil {
		return m.RewardWeightFailedTxs
	}
	return ""
}

func (m *QueryParamsResponse) GetDefaultBlockTimeMs() int64 {
	if m != nil {
		return m.DefaultBlockTimeMs
	}
	return 0
}

func (m *QueryParamsResponse) GetDefaultBaseGasPrice() string {
	if m != nil {
		return m.DefaultBaseGasPrice
	}
	return ""
}

func (m *QueryParamsResponse) GetDefaultValidatorSetSize() uint64 {
	if m != nil {
		return m.DefaultValidatorSetSize
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryAgentStatusRequest)(nil), "qorechain.rlconsensus.v1.QueryAgentStatusRequest")
	proto.RegisterType((*QueryAgentStatusResponse)(nil), "qorechain.rlconsensus.v1.QueryAgentStatusResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "qorechain.rlconsensus.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "qorechain.rlconsensus.v1.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("qorechain/rlconsensus/v1/query.proto", fileDescriptor_e1b919a53aee72c3)
}

var fileDescriptor_e1b919a53aee72c3 = []byte{
	// 791 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x41, 0x6f, 0xdb, 0x36,
	0x14, 0xc7, 0xa3, 0x26, 0x4d, 0x63, 0x26, 0x6d, 0x50, 0xda, 0x49, 0xd8, 0x60, 0x73, 0x83, 0xac,
	0x87, 0x1c, 0x56, 0x1b, 0x4e, 0x87, 0x75, 0xd8, 0x0e, 0x83, 0xd3, 0x76, 0xc3, 0x0e, 0xc1, 0x5a,
	0x39, 0x68, 0x81, 0x5d, 0x08, 0x5a, 0x7a, 0x91, 0x88, 0x4a, 0xa2, 0x43, 0x52, 0x8a, 0x93, 0x4f,
	0xb1, 0x8f, 0xb2, 0xc3, 0x3e, 0xc4, 0x8e, 0x3d, 0xee, 0x34, 0x0c, 0xce, 0x3e, 0xc8, 0xc0, 0x27,
	0xd9, 0x95, 0xbc, 0x15, 0x5b, 0x6f, 0xcc, 0xfb, 0xfd, 0xff, 0x0c, 0xf5, 0x7f, 0xe4, 0x33, 0x79,
	0x74, 0xa1, 0x34, 0x04, 0xb1, 0x90, 0x59, 0x5f, 0x27, 0x81, 0xca, 0x0c, 0x64, 0x26, 0x37, 0xfd,
	0x62, 0xd0, 0xbf, 0xc8, 0x41, 0x5f, 0xf5, 0x26, 0x5a, 0x59, 0x45, 0xd9, 0x42, 0xd5, 0xab, 0xa9,
	0x7a, 0xc5, 0x60, 0xbf, 0x13, 0xa9, 0x48, 0xa1, 0xa8, 0xef, 0x56, 0xa5, 0xfe, 0xf0, 0x01, 0xd9,
	0x7b, 0xe5, 0xec, 0xc3, 0x08, 0x32, 0x3b, 0xb2, 0xc2, 0xe6, 0xc6, 0x87, 0x8b, 0x1c, 0x8c, 0x3d,
	0xfc, 0xe5, 0x16, 0x61, 0xff, 0x64, 0x66, 0xe2, 0x36, 0xa5, 0x94, 0xac, 0xa5, 0x2a, 0x04, 0xe6,
	0x1d, 0x78, 0x47, 0x2d, 0x1f, 0xd7, 0xf4, 0x33, 0x72, 0x37, 0xc8, 0xb5, 0x86, 0xcc, 0x72, 0x98,
	0xa8, 0x20, 0x66, 0xb7, 0x0e, 0xbc, 0xa3, 0x35, 0x7f, 0xab, 0x2a, 0xbe, 0x70, 0x35, 0xfa, 0x90,
	0x6c, 0x5a, 0x65, 0x45, 0xc2, 0x8d, 0x85, 0x89, 0x61, 0xab, 0x28, 0x21, 0x58, 0x1a, 0xb9, 0x0a,
	0xed, 0x91, 0x76, 0x22, 0x8c, 0xe5, 0x6a, 0x6c, 0x40, 0x17, 0xc2, 0x4a, 0x95, 0x71, 0x61, 0xd9,
	0xda, 0x81, 0x77, 0xb4, 0xea, 0xdf, 0x77, 0xe8, 0xc7, 0xf7, 0x64, 0x68, 0xe9, 0x23, 0x72, 0x0f,
	0xf5, 0x22, 0x98, 0x4b, 0x6f, 0xa3, 0x74, 0xcb, 0x55, 0x87, 0x41, 0xa5, 0xfa, 0x82, 0xec, 0x06,
	0x52, 0x07, 0xb9, 0xb4, 0x7c, 0xac, 0x41, 0xbc, 0x05, 0x8d, 0x86, 0x02, 0xd8, 0xfa, 0x81, 0x77,
	0xb4, 0xe1, 0x77, 0x2a, 0x7a, 0x52, 0xc2, 0x21, 0x32, 0x77, 0x96, 0x71, 0xa2, 0x82, 0xb7, 0x86,
	0x1b, 0x99, 0x05, 0xc0, 0x35, 0x14, 0xa0, 0x2d, 0xbb, 0x53, 0x9e, 0xa5, 0x44, 0x23, 0x47, 0x7c,
	0x04, 0x87, 0x1d, 0x42, 0x31, 0xb1, 0x97, 0x42, 0x8b, 0x74, 0x11, 0xe4, 0xaf, 0xeb, 0xa4, 0xdd,
	0x28, 0x57, 0x19, 0x32, 0x72, 0x07, 0x32, 0x31, 0x4e, 0x20, 0xc4, 0x18, 0x37, 0xfc, 0xf9, 0x9f,
	0x74, 0x40, 0x3a, 0xf5, 0xcf, 0x97, 0x99, 0x75, 0xeb, 0xa4, 0x0a, 0xb4, 0x5d, 0x63, 0x3f, 0x54,
	0x88, 0x7e, 0x4a, 0x88, 0x70, 0x7d, 0xe2, 0xd8, 0x96, 0x55, 0x6c, 0x4b, 0x0b, 0x2b, 0xa7, 0xae,
	0x37, 0x5f, 0x92, 0xbd, 0x54, 0x4c, 0x79, 0x10, 0x8b, 0x2c, 0x02, 0x8e, 0x17, 0x03, 0x77, 0x28,
	0x00, 0x93, 0x6d, 0xf9, 0x3b, 0xa9, 0x98, 0x3e, 0x43, 0xfa, 0xac, 0x06, 0xe9, 0x31, 0xd9, 0xa9,
	0xf9, 0x44, 0x6e, 0x55, 0xa6, 0x52, 0x95, 0x1b, 0x0c, 0xb9, 0xe5, 0xb7, 0x17, 0xae, 0xe1, 0x02,
	0xfd, 0x5b, 0xd6, 0x97, 0x32, 0x0b, 0xd5, 0x25, 0x66, 0xbd, 0xb6, 0x9c, 0xf5, 0x1b, 0x64, 0xf4,
	0x6b, 0xf2, 0x60, 0xd9, 0x65, 0x63, 0x0d, 0x26, 0x56, 0x49, 0x88, 0x89, 0xb7, 0xfc, 0xbd, 0xa6,
	0xf1, 0x6c, 0x8e, 0xe9, 0x57, 0x84, 0x69, 0xb8, 0x14, 0x3a, 0xe4, 0x97, 0x20, 0xa3, 0xd8, 0x3a,
	0xa7, 0xca, 0xa3, 0x78, 0x92, 0x5b, 0xb6, 0x81, 0xd6, 0xdd, 0x92, 0xbf, 0x41, 0x7c, 0xb6, 0xa0,
	0xee, 0xac, 0x4d, 0xe7, 0xb9, 0xcc, 0x44, 0x22, 0xed, 0x15, 0x6b, 0xa1, 0xaf, 0x53, 0xf7, 0x7d,
	0x57, 0x31, 0xfa, 0x9c, 0x74, 0x9b, 0xae, 0x10, 0x02, 0xc8, 0xac, 0x16, 0x89, 0xbc, 0xc6, 0xb6,
	0x30, 0x82, 0xee, 0x4f, 0xea, 0xee, 0xe7, 0x4b, 0x1a, 0xfa, 0x2d, 0xb9, 0xdf, 0xdc, 0x25, 0x85,
	0x82, 0x6d, 0x3a, 0xe3, 0x49, 0x7b, 0xf6, 0xc7, 0xc3, 0x6d, 0xbf, 0x66, 0x3e, 0x7d, 0xf1, 0xda,
	0xdf, 0xae, 0xef, 0x76, 0x0a, 0x05, 0x7d, 0xba, 0xfc, 0xd9, 0xe7, 0x42, 0x26, 0x10, 0x72, 0x3b,
	0x35, 0x6c, 0xab, 0xec, 0x6a, 0xe3, 0xf8, 0x48, 0xcf, 0xa6, 0x86, 0x0e, 0xc8, 0x4e, 0x08, 0xe7,
	0x22, 0x4f, 0x2c, 0xc7, 0x4b, 0xcc, 0xad, 0x4c, 0x81, 0xa7, 0x86, 0xdd, 0xc5, 0x9b, 0x4d, 0x2b,
	0x78, 0xe2, 0xd8, 0x99, 0x4c, 0xe1, 0xd4, 0xd0, 0x27, 0x64, 0x77, 0x61, 0x11, 0x06, 0x78, 0x24,
	0x0c, 0x9f, 0x68, 0x19, 0x00, 0xbb, 0x57, 0xde, 0x84, 0xb9, 0x47, 0x18, 0xf8, 0x5e, 0x98, 0x97,
	0x0e, 0xd1, 0x6f, 0xc8, 0xfe, 0xdc, 0x54, 0x88, 0x44, 0x86, 0xc2, 0x2a, 0xcd, 0x0d, 0x58, 0x6e,
	0xe4, 0x35, 0xb0, 0x6d, 0xbc, 0x0d, 0x7b, 0x95, 0xe2, 0xf5, 0x5c, 0x30, 0x02, 0x3b, 0x92, 0xd7,
	0x70, 0xfc, 0x97, 0x47, 0x6e, 0xe3, 0xb3, 0xa1, 0x96, 0x6c, 0xd6, 0x66, 0x10, 0x1d, 0xf4, 0x3e,
	0x34, 0xe4, 0x7a, 0x1f, 0x98, 0x65, 0xfb, 0xc7, 0x1f, 0x63, 0xa9, 0x9e, 0x27, 0x90, 0xf5, 0xf2,
	0xc1, 0xd2, 0xcf, 0xff, 0xc3, 0xdd, 0x78, 0xee, 0xfb, 0x8f, 0xff, 0xa7, 0xba, 0xfc, 0x37, 0x27,
	0xaf, 0x7e, 0x9b, 0x75, 0xbd, 0x77, 0xb3, 0xae, 0xf7, 0xe7, 0xac, 0xeb, 0xfd, 0x7c, 0xd3, 0x5d,
	0x79, 0x77, 0xd3, 0x5d, 0xf9, 0xfd, 0xa6, 0xbb, 0xf2, 0xd3, 0xd3, 0x48, 0xda, 0x38, 0x1f, 0xf7,
	0x02, 0x95, 0xf6, 0xdf, 0x0f, 0xff, 0xc5, 0xea, 0x71, 0xa0, 0x34, 0xf4, 0xa7, 0x8d, 0x5f, 0x03,
	0x7b, 0x35, 0x01, 0x33, 0x5e, 0xc7, 0xd9, 0xfe, 0xe4, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79,
	0x97, 0x8a, 0x02, 0x33, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// AgentStatus returns the live RL agent status (epoch, steps, mode).
	AgentStatus(ctx context.Context, in *QueryAgentStatusRequest, opts ...grpc.CallOption) (*QueryAgentStatusResponse, error)
	// Params returns the rlconsensus module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) AgentStatus(ctx context.Context, in *QueryAgentStatusRequest, opts ...grpc.CallOption) (*QueryAgentStatusResponse, error) {
	out := new(QueryAgentStatusResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rlconsensus.v1.Query/AgentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rlconsensus.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// AgentStatus returns the live RL agent status (epoch, steps, mode).
	AgentStatus(context.Context, *QueryAgentStatusRequest) (*QueryAgentStatusResponse, error)
	// Params returns the rlconsensus module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) AgentStatus(ctx context.Context, req *QueryAgentStatusRequest) (*QueryAgentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentStatus not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_AgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rlconsensus.v1.Query/AgentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AgentStatus(ctx, req.(*QueryAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rlconsensus.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.rlconsensus.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgentStatus",
			Handler:    _Query_AgentStatus_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/rlconsensus/v1/query.proto",
}

func (m *QueryAgentStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAgentStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAgentStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAgentStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAgentStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAgentStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlocksSinceRevert != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlocksSinceRevert))
		i--
		dAtA[i] = 0x38
	}
	if m.CircuitBreakerActive {
		i--
		if m.CircuitBreakerActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.LastActionAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastActionAt))
		i--
		dAtA[i] = 0x28
	}
	if m.LastObservationAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastObservationAt))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalSteps != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalSteps))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DefaultValidatorSetSize != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DefaultValidatorSetSize))
		i--
		dAtA[i] = 0x78
	}
	if len(m.DefaultBaseGasPrice) > 0 {
		i -= len(m.DefaultBaseGasPrice)
		copy(dAtA[i:], m.DefaultBaseGasPrice)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DefaultBaseGasPrice)))
		i--
		dAtA[i] = 0x72
	}
	if m.DefaultBlockTimeMs != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DefaultBlockTimeMs))
		i--
		dAtA[i] = 0x68
	}
	if len(m.RewardWeightFailedTxs) > 0 {
		i -= len(m.RewardWeightFailedTxs)
		copy(dAtA[i:], m.RewardWeightFailedTxs)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RewardWeightFailedTxs)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.RewardWeightMEV) > 0 {
		i -= len(m.RewardWeightMEV)
		copy(dAtA[i:], m.RewardWeightMEV)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RewardWeightMEV)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.RewardWeightDecentralization) > 0 {
		i -= len(m.RewardWeightDecentralization)
		copy(dAtA[i:], m.RewardWeightDecentralization)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RewardWeightDecentralization)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.RewardWeightFinality) > 0 {
		i -= len(m.RewardWeightFinality)
		copy(dAtA[i:], m.RewardWeightFinality)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RewardWeightFinality)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RewardWeightThroughput) > 0 {
		i -= len(m.RewardWeightThroughput)
		copy(dAtA[i:], m.RewardWeightThroughput)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RewardWeightThroughput)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.CircuitBreakerThreshold) > 0 {
		i -= len(m.CircuitBreakerThreshold)
		copy(dAtA[i:], m.CircuitBreakerThreshold)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CircuitBreakerThreshold)))
		i--
		dAtA[i] = 0x3a
	}
	if m.CircuitBreakerWindow != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CircuitBreakerWindow))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MaxChangeAutonomous) > 0 {
		i -= len(m.MaxChangeAutonomous)
		copy(dAtA[i:], m.MaxChangeAutonomous)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MaxChangeAutonomous)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MaxChangeConservative) > 0 {
		i -= len(m.MaxChangeConservative)
		copy(dAtA[i:], m.MaxChangeConservative)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MaxChangeConservative)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AgentMode) > 0 {
		i -= len(m.AgentMode)
		copy(dAtA[i:], m.AgentMode)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AgentMode)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ObservationInterval != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ObservationInterval))
		i--
		dAtA[i] = 0x10
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAgentStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAgentStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CurrentEpoch != 0 {
		n += 1 + sovQuery(uint64(m.CurrentEpoch))
	}
	if m.TotalSteps != 0 {
		n += 1 + sovQuery(uint64(m.TotalSteps))
	}
	if m.LastObservationAt != 0 {
		n += 1 + sovQuery(uint64(m.LastObservationAt))
	}
	if m.LastActionAt != 0 {
		n += 1 + sovQuery(uint64(m.LastActionAt))
	}
	if m.CircuitBreakerActive {
		n += 2
	}
	if m.BlocksSinceRevert != 0 {
		n += 1 + sovQuery(uint64(m.BlocksSinceRevert))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	if m.ObservationInterval != 0 {
		n += 1 + sovQuery(uint64(m.ObservationInterval))
	}
	l = len(m.AgentMode)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.MaxChangeConservative)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.MaxChangeAutonomous)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CircuitBreakerWindow != 0 {
		n += 1 + sovQuery(uint64(m.CircuitBreakerWindow))
	}
	l = len(m.CircuitBreakerThreshold)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RewardWeightThroughput)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RewardWeightFinality)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RewardWeightDecentralization)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RewardWeightMEV)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RewardWeightFailedTxs)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.DefaultBlockTimeMs != 0 {
		n += 1 + sovQuery(uint64(m.DefaultBlockTimeMs))
	}
	l = len(m.DefaultBaseGasPrice)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.DefaultValidatorSetSize != 0 {
		n += 1 + sovQuery(uint64(m.DefaultValidatorSetSize))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAgentStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAgentStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAgentStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAgentStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAgentStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAgentStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSteps", wireType)
			}
			m.TotalSteps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSteps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastObservationAt", wireType)
			}
			m.LastObservationAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastObservationAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastActionAt", wireType)
			}
			m.LastActionAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastActionAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitBreakerActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CircuitBreakerActive = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksSinceRevert", wireType)
			}
			m.BlocksSinceRevert = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksSinceRevert |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservationInterval", wireType)
			}
			m.ObservationInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservationInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentMode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentMode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChangeConservative", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxChangeConservative = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChangeAutonomous", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxChangeAutonomous = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitBreakerWindow", wireType)
			}
			m.CircuitBreakerWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CircuitBreakerWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitBreakerThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitBreakerThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeightThroughput", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardWeightThroughput = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeightFinality", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardWeightFinality = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeightDecentralization", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardWeightDecentralization = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeightMEV", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardWeightMEV = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeightFailedTxs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardWeightFailedTxs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultBlockTimeMs", wireType)
			}
			m.DefaultBlockTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultBlockTimeMs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultBaseGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultBaseGasPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultValidatorSetSize", wireType)
			}
			m.DefaultValidatorSetSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultValidatorSetSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
