// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/license/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LicenseView is the query-facing view of a license grant.
type LicenseView struct {
	Grantee   string `protobuf:"bytes,1,opt,name=grantee,proto3" json:"grantee,omitempty"`
	FeatureId string `protobuf:"bytes,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	ExpiresAt int64  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	GrantedAt int64  `protobuf:"varint,4,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	GrantedBy string `protobuf:"bytes,5,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	Suspended bool   `protobuf:"varint,6,opt,name=suspended,proto3" json:"suspended,omitempty"`
	Metadata  string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *LicenseView) Reset()         { *m = LicenseView{} }
func (m *LicenseView) String() string { return proto.CompactTextString(m) }
func (*LicenseView) ProtoMessage()    {}
func (*LicenseView) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{0}
}
func (m *LicenseView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LicenseView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LicenseView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LicenseView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LicenseView.Merge(m, src)
}
func (m *LicenseView) XXX_Size() int {
	return m.Size()
}
func (m *LicenseView) XXX_DiscardUnknown() {
	xxx_messageInfo_LicenseView.DiscardUnknown(m)
}

var xxx_messageInfo_LicenseView proto.InternalMessageInfo

func (m *LicenseView) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

func (m *LicenseView) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *LicenseView) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *LicenseView) GetGrantedAt() int64 {
	if m != nil {
		return m.GrantedAt
	}
	return 0
}

func (m *LicenseView) GetGrantedBy() string {
	if m != nil {
		return m.GrantedBy
	}
	return ""
}

func (m *LicenseView) GetSuspended() bool {
	if m != nil {
		return m.Suspended
	}
	return false
}

func (m *LicenseView) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type QueryCheckRequest struct {
	Grantee   string `protobuf:"bytes,1,opt,name=grantee,proto3" json:"grantee,omitempty"`
	FeatureId string `protobuf:"bytes,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
}

func (m *QueryCheckRequest) Reset()         { *m = QueryCheckRequest{} }
func (m *QueryCheckRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCheckRequest) ProtoMessage()    {}
func (*QueryCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{1}
}
func (m *QueryCheckRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCheckRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCheckRequest.Merge(m, src)
}
func (m *QueryCheckRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCheckRequest proto.InternalMessageInfo

func (m *QueryCheckRequest) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

func (m *QueryCheckRequest) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

type QueryCheckResponse struct {
	License *LicenseView `protobuf:"bytes,1,opt,name=license,proto3" json:"license,omitempty"`
	// active is true when the grant exists and is not suspended.
	Active bool `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *QueryCheckResponse) Reset()         { *m = QueryCheckResponse{} }
func (m *QueryCheckResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCheckResponse) ProtoMessage()    {}
func (*QueryCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{2}
}
func (m *QueryCheckResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCheckResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCheckResponse.Merge(m, src)
}
func (m *QueryCheckResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCheckResponse proto.InternalMessageInfo

func (m *QueryCheckResponse) GetLicense() *LicenseView {
	if m != nil {
		return m.License
	}
	return nil
}

func (m *QueryCheckResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type QueryHoldersRequest struct {
	FeatureId string `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
}

func (m *QueryHoldersRequest) Reset()         { *m = QueryHoldersRequest{} }
func (m *QueryHoldersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryHoldersRequest) ProtoMessage()    {}
func (*QueryHoldersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{3}
}
func (m *QueryHoldersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHoldersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHoldersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHoldersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHoldersRequest.Merge(m, src)
}
func (m *QueryHoldersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryHoldersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHoldersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHoldersRequest proto.InternalMessageInfo

func (m *QueryHoldersRequest) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

type QueryHoldersResponse struct {
	Licenses []*LicenseView `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
}

func (m *QueryHoldersResponse) Reset()         { *m = QueryHoldersResponse{} }
func (m *QueryHoldersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryHoldersResponse) ProtoMessage()    {}
func (*QueryHoldersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{4}
}
func (m *QueryHoldersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHoldersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHoldersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHoldersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHoldersResponse.Merge(m, src)
}
func (m *QueryHoldersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryHoldersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHoldersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHoldersResponse proto.InternalMessageInfo

func (m *QueryHoldersResponse) GetLicenses() []*LicenseView {
	if m != nil {
		return m.Licenses
	}
	return nil
}

type QueryListRequest struct {
	Grantee string `protobuf:"bytes,1,opt,name=grantee,proto3" json:"grantee,omitempty"`
}

func (m *QueryListRequest) Reset()         { *m = QueryListRequest{} }
func (m *QueryListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListRequest) ProtoMessage()    {}
func (*QueryListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{5}
}
func (m *QueryListRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListRequest.Merge(m, src)
}
func (m *QueryListRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListRequest proto.InternalMessageInfo

func (m *QueryListRequest) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

type QueryListResponse struct {
	Licenses []*LicenseView `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
}

func (m *QueryListResponse) Reset()         { *m = QueryListResponse{} }
func (m *QueryListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListResponse) ProtoMessage()    {}
func (*QueryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e1b2ae184fa79f0, []int{6}
}
func (m *QueryListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListResponse.Merge(m, src)
}
func (m *QueryListResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListResponse proto.InternalMessageInfo

func (m *QueryListResponse) GetLicenses() []*LicenseView {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func init() {
	proto.RegisterType((*LicenseView)(nil), "qorechain.license.v1.LicenseView")
	proto.RegisterType((*QueryCheckRequest)(nil), "qorechain.license.v1.QueryCheckRequest")
	proto.RegisterType((*QueryCheckResponse)(nil), "qorechain.license.v1.QueryCheckResponse")
	proto.RegisterType((*QueryHoldersRequest)(nil), "qorechain.license.v1.QueryHoldersRequest")
	proto.RegisterType((*QueryHoldersResponse)(nil), "qorechain.license.v1.QueryHoldersResponse")
	proto.RegisterType((*QueryListRequest)(nil), "qorechain.license.v1.QueryListRequest")
	proto.RegisterType((*QueryListResponse)(nil), "qorechain.license.v1.QueryListResponse")
}

func init() { proto.RegisterFile("qorechain/license/v1/query.proto", fileDescriptor_6e1b2ae184fa79f0) }

var fileDescriptor_6e1b2ae184fa79f0 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0x36, 0xcd, 0xd7, 0xf4, 0x02, 0x4b, 0x85, 0x56, 0x11, 0x58, 0xc6, 0x07, 0x1a, 0x10,
	0xd8, 0x6a, 0xcb, 0x0d, 0x71, 0xa0, 0x5c, 0x40, 0x0a, 0x07, 0x2c, 0x01, 0x52, 0x2f, 0x65, 0x63,
	0x0f, 0xcd, 0x8a, 0xd6, 0x76, 0x76, 0xd7, 0xa1, 0xf9, 0x17, 0xfc, 0x02, 0x7e, 0x0f, 0xc7, 0x1e,
	0xb9, 0x20, 0xa1, 0xe4, 0x8f, 0x20, 0xaf, 0x37, 0x6e, 0x0c, 0x55, 0x53, 0xa1, 0xde, 0x3c, 0x33,
	0xef, 0xbd, 0x79, 0x7e, 0x2b, 0x0d, 0xb8, 0x93, 0x54, 0x62, 0x34, 0xe6, 0x22, 0x09, 0x4e, 0x44,
	0x84, 0x89, 0xc2, 0x60, 0xba, 0x1b, 0x4c, 0x72, 0x94, 0x33, 0x3f, 0x93, 0xa9, 0x4e, 0xe9, 0x76,
	0x85, 0xf0, 0x2d, 0xc2, 0x9f, 0xee, 0x7a, 0xbf, 0x08, 0x6c, 0x0d, 0xcb, 0xf2, 0x83, 0xc0, 0xaf,
	0x94, 0x41, 0xe7, 0x58, 0xf2, 0x44, 0x23, 0x32, 0xe2, 0x92, 0x41, 0x2f, 0x5c, 0x96, 0xf4, 0x3e,
	0xc0, 0x67, 0xe4, 0x3a, 0x97, 0x78, 0x24, 0x62, 0xb6, 0x61, 0x86, 0x3d, 0xdb, 0x79, 0x13, 0x17,
	0x63, 0x3c, 0xcb, 0x84, 0x44, 0x75, 0xc4, 0x35, 0x6b, 0xba, 0x64, 0xd0, 0x0c, 0x7b, 0xb6, 0xf3,
	0x52, 0x17, 0xe3, 0x52, 0x28, 0x2e, 0xc6, 0x9b, 0xe5, 0xd8, 0x76, 0xea, 0xe3, 0xd1, 0x8c, 0xb5,
	0x4a, 0x71, 0xdb, 0x39, 0x98, 0xd1, 0x7b, 0xd0, 0x53, 0xb9, 0xca, 0x30, 0x89, 0x31, 0x66, 0x6d,
	0x97, 0x0c, 0xba, 0xe1, 0x45, 0x83, 0xf6, 0xa1, 0x7b, 0x8a, 0x9a, 0xc7, 0x5c, 0x73, 0xd6, 0x31,
	0xd4, 0xaa, 0xf6, 0x86, 0x70, 0xfb, 0x5d, 0x11, 0xc2, 0xab, 0x31, 0x46, 0x5f, 0x42, 0x9c, 0xe4,
	0xa8, 0xf4, 0x7f, 0xff, 0xa4, 0x27, 0x80, 0xae, 0xaa, 0xa9, 0x2c, 0x4d, 0x14, 0xd2, 0xe7, 0xd0,
	0xb1, 0x89, 0x1a, 0xb9, 0xad, 0xbd, 0x07, 0xfe, 0x65, 0x59, 0xfb, 0x2b, 0x39, 0x87, 0x4b, 0x06,
	0xbd, 0x0b, 0x6d, 0x1e, 0x69, 0x31, 0x45, 0xb3, 0xad, 0x1b, 0xda, 0xca, 0x7b, 0x06, 0x77, 0xcc,
	0xaa, 0xd7, 0xe9, 0x49, 0x8c, 0x52, 0x2d, 0xad, 0xd7, 0x0d, 0x92, 0xbf, 0x0d, 0xbe, 0x87, 0xed,
	0x3a, 0xcb, 0x5a, 0x7c, 0x01, 0x5d, 0xbb, 0x50, 0x31, 0xe2, 0x36, 0xaf, 0xe7, 0xb1, 0xa2, 0x78,
	0x4f, 0xe0, 0x96, 0x91, 0x1d, 0x0a, 0xa5, 0xd7, 0x86, 0xe8, 0x85, 0x36, 0xf3, 0x12, 0x7d, 0x23,
	0x0e, 0xf6, 0xbe, 0x6f, 0x40, 0xcb, 0x88, 0xd2, 0x43, 0x68, 0x99, 0xf8, 0xe9, 0xce, 0xe5, 0xfc,
	0x7f, 0x9e, 0xbb, 0x3f, 0x58, 0x0f, 0xb4, 0x26, 0x3f, 0x41, 0xc7, 0x26, 0x47, 0x1f, 0x5d, 0x41,
	0xaa, 0xbf, 0x49, 0xff, 0xf1, 0x75, 0xa0, 0x76, 0xc3, 0x47, 0xd8, 0x2c, 0x62, 0xa1, 0x0f, 0xaf,
	0xe0, 0xac, 0xa4, 0xdc, 0xdf, 0x59, 0x8b, 0x2b, 0x85, 0x0f, 0xde, 0xfe, 0x98, 0x3b, 0xe4, 0x7c,
	0xee, 0x90, 0xdf, 0x73, 0x87, 0x7c, 0x5b, 0x38, 0x8d, 0xf3, 0x85, 0xd3, 0xf8, 0xb9, 0x70, 0x1a,
	0x87, 0xfb, 0xc7, 0x42, 0x8f, 0xf3, 0x91, 0x1f, 0xa5, 0xa7, 0xc1, 0xc5, 0x95, 0xa8, 0xbe, 0x9e,
	0x46, 0xa9, 0xc4, 0xe0, 0xac, 0x3a, 0x1b, 0x7a, 0x96, 0xa1, 0x1a, 0xb5, 0xcd, 0xd1, 0xd8, 0xff,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xa5, 0xc6, 0x3e, 0x58, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Check returns a single license grant for (grantee, feature_id).
	Check(ctx context.Context, in *QueryCheckRequest, opts ...grpc.CallOption) (*QueryCheckResponse, error)
	// Holders lists every grantee holding a given feature license.
	Holders(ctx context.Context, in *QueryHoldersRequest, opts ...grpc.CallOption) (*QueryHoldersResponse, error)
	// List returns every license held by a grantee.
	List(ctx context.Context, in *QueryListRequest, opts ...grpc.CallOption) (*QueryListResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Check(ctx context.Context, in *QueryCheckRequest, opts ...grpc.CallOption) (*QueryCheckResponse, error) {
	out := new(QueryCheckResponse)
	err := c.cc.Invoke(ctx, "/qorechain.license.v1.Query/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Holders(ctx context.Context, in *QueryHoldersRequest, opts ...grpc.CallOption) (*QueryHoldersResponse, error) {
	out := new(QueryHoldersResponse)
	err := c.cc.Invoke(ctx, "/qorechain.license.v1.Query/Holders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) List(ctx context.Context, in *QueryListRequest, opts ...grpc.CallOption) (*QueryListResponse, error) {
	out := new(QueryListResponse)
	err := c.cc.Invoke(ctx, "/qorechain.license.v1.Query/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Check returns a single license grant for (grantee, feature_id).
	Check(context.Context, *QueryCheckRequest) (*QueryCheckResponse, error)
	// Holders lists every grantee holding a given feature license.
	Holders(context.Context, *QueryHoldersRequest) (*QueryHoldersResponse, error)
	// List returns every license held by a grantee.
	List(context.Context, *QueryListRequest) (*QueryListResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Check(ctx context.Context, req *QueryCheckRequest) (*QueryCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedQueryServer) Holders(ctx context.Context, req *QueryHoldersRequest) (*QueryHoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Holders not implemented")
}
func (*UnimplementedQueryServer) List(ctx context.Context, req *QueryListRequest) (*QueryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.license.v1.Query/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Check(ctx, req.(*QueryCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Holders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Holders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.license.v1.Query/Holders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Holders(ctx, req.(*QueryHoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.license.v1.Query/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).List(ctx, req.(*QueryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.license.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Query_Check_Handler,
		},
		{
			MethodName: "Holders",
			Handler:    _Query_Holders_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Query_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/license/v1/query.proto",
}

func (m *LicenseView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LicenseView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LicenseView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Suspended {
		i--
		if m.Suspended {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.GrantedBy) > 0 {
		i -= len(m.GrantedBy)
		copy(dAtA[i:], m.GrantedBy)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.GrantedBy)))
		i--
		dAtA[i] = 0x2a
	}
	if m.GrantedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.GrantedAt))
		i--
		dAtA[i] = 0x20
	}
	if m.ExpiresAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ExpiresAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.FeatureId) > 0 {
		i -= len(m.FeatureId)
		copy(dAtA[i:], m.FeatureId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeatureId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Grantee) > 0 {
		i -= len(m.Grantee)
		copy(dAtA[i:], m.Grantee)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Grantee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCheckRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCheckRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCheckRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeatureId) > 0 {
		i -= len(m.FeatureId)
		copy(dAtA[i:], m.FeatureId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeatureId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Grantee) > 0 {
		i -= len(m.Grantee)
		copy(dAtA[i:], m.Grantee)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Grantee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCheckResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCheckResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCheckResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.License != nil {
		{
			size, err := m.License.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryHoldersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHoldersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHoldersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeatureId) > 0 {
		i -= len(m.FeatureId)
		copy(dAtA[i:], m.FeatureId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FeatureId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryHoldersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHoldersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHoldersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Licenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Grantee) > 0 {
		i -= len(m.Grantee)
		copy(dAtA[i:], m.Grantee)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Grantee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for iNdEx := len(m.Licenses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Licenses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LicenseView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Grantee)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.FeatureId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ExpiresAt != 0 {
		n += 1 + sovQuery(uint64(m.ExpiresAt))
	}
	if m.GrantedAt != 0 {
		n += 1 + sovQuery(uint64(m.GrantedAt))
	}
	l = len(m.GrantedBy)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Suspended {
		n += 2
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCheckRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Grantee)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.FeatureId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCheckResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.License != nil {
		l = m.License.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Active {
		n += 2
	}
	return n
}

func (m *QueryHoldersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeatureId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryHoldersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for _, e := range m.Licenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryListRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Grantee)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Licenses) > 0 {
		for _, e := range m.Licenses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LicenseView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LicenseView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LicenseView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grantee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grantee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeatureId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeatureId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			m.ExpiresAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrantedAt", wireType)
			}
			m.GrantedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GrantedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrantedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrantedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Suspended", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Suspended = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCheckRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCheckRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCheckRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grantee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grantee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeatureId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeatureId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCheckResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCheckResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCheckResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field License", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.License == nil {
				m.License = &LicenseView{}
			}
			if err := m.License.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHoldersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHoldersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHoldersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeatureId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeatureId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHoldersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHoldersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHoldersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, &LicenseView{})
			if err := m.Licenses[len(m.Licenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grantee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grantee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Licenses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Licenses = append(m.Licenses, &LicenseView{})
			if err := m.Licenses[len(m.Licenses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
