package indexer

import (
	"context"
	"database/sql"

	// PostgreSQL driver for database/sql.
	_ "github.com/lib/pq"
)

// Rows abstracts the result set returned by a query. Implementations wrap
// the driver-specific row iterator.
type Rows interface {
	// Next advances to the next row. Returns false when no more rows remain.
	Next() bool
	// Scan copies the current row's columns into dest values.
	Scan(dest ...any) error
	// Close releases the resources held by the row iterator.
	Close() error
	// Err returns any error encountered during iteration.
	Err() error
}

// Result abstracts the result of an exec (INSERT, UPDATE, DELETE) operation.
type Result interface {
	// RowsAffected returns the number of rows affected by the statement.
	RowsAffected() (int64, error)
	// LastInsertId returns the integer generated by the database in response
	// to a command. Not all databases support this.
	LastInsertId() (int64, error)
}

// DBProvider is an abstraction over database access. It exposes the minimal
// surface area needed by the block indexer, making it straightforward to swap
// the underlying driver without touching business logic.
//
// Current implementation: StdSQLProvider (database/sql + lib/pq).
// Future: NewPgxProvider(connStr string) uses jackc/pgx/v5 for better performance
// including native COPY support, pipelining, and connection pool management.
type DBProvider interface {
	// Query executes a query that returns rows (SELECT).
	Query(ctx context.Context, query string, args ...any) (Rows, error)
	// Exec executes a statement that does not return rows (INSERT, UPDATE, DELETE).
	Exec(ctx context.Context, query string, args ...any) (Result, error)
	// Close releases the underlying database connection and associated resources.
	Close() error
}

// ---------------------------------------------------------------------------
// StdSQLProvider — database/sql + lib/pq
// ---------------------------------------------------------------------------

// StdSQLProvider implements DBProvider using Go's standard database/sql
// package with the lib/pq PostgreSQL driver.
type StdSQLProvider struct {
	db *sql.DB
}

// NewStdSQLProvider opens a PostgreSQL connection using database/sql and
// returns a provider that satisfies the DBProvider interface.
//
// connStr is a PostgreSQL connection string, e.g.:
//
//	"postgres://user:pass@localhost:5432/qorechain_indexer?sslmode=disable"
func NewStdSQLProvider(connStr string) (*StdSQLProvider, error) {
	db, err := sql.Open("postgres", connStr)
	if err != nil {
		return nil, err
	}
	// Verify the connection is reachable.
	if err := db.Ping(); err != nil {
		db.Close()
		return nil, err
	}
	return &StdSQLProvider{db: db}, nil
}

// stdSQLRows wraps *sql.Rows to satisfy the Rows interface.
type stdSQLRows struct {
	rows *sql.Rows
}

func (r *stdSQLRows) Next() bool         { return r.rows.Next() }
func (r *stdSQLRows) Scan(dest ...any) error { return r.rows.Scan(dest...) }
func (r *stdSQLRows) Close() error        { return r.rows.Close() }
func (r *stdSQLRows) Err() error          { return r.rows.Err() }

// stdSQLResult wraps sql.Result to satisfy the Result interface.
type stdSQLResult struct {
	result sql.Result
}

func (r *stdSQLResult) RowsAffected() (int64, error) { return r.result.RowsAffected() }
func (r *stdSQLResult) LastInsertId() (int64, error)  { return r.result.LastInsertId() }

// Query executes a SELECT query and returns wrapped rows.
func (p *StdSQLProvider) Query(ctx context.Context, query string, args ...any) (Rows, error) {
	rows, err := p.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	return &stdSQLRows{rows: rows}, nil
}

// Exec executes an INSERT/UPDATE/DELETE statement.
func (p *StdSQLProvider) Exec(ctx context.Context, query string, args ...any) (Result, error) {
	result, err := p.db.ExecContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	return &stdSQLResult{result: result}, nil
}

// Close shuts down the underlying *sql.DB connection pool.
func (p *StdSQLProvider) Close() error {
	return p.db.Close()
}

// DB returns the underlying *sql.DB for callers that need direct access
// (e.g., for migrations or driver-specific operations).
func (p *StdSQLProvider) DB() *sql.DB {
	return p.db
}
