// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/crossvm/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCrossVMCall struct {
	Sender         string                                   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	SourceVM       VMType                                   `protobuf:"bytes,2,opt,name=source_vm,json=sourceVm,proto3,casttype=VMType" json:"source_vm,omitempty"`
	TargetVM       VMType                                   `protobuf:"bytes,3,opt,name=target_vm,json=targetVm,proto3,casttype=VMType" json:"target_vm,omitempty"`
	TargetContract string                                   `protobuf:"bytes,4,opt,name=target_contract,json=targetContract,proto3" json:"target_contract,omitempty"`
	Payload        []byte                                   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Funds          github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,6,rep,name=funds,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"funds"`
}

func (m *MsgCrossVMCall) Reset()         { *m = MsgCrossVMCall{} }
func (m *MsgCrossVMCall) String() string { return proto.CompactTextString(m) }
func (*MsgCrossVMCall) ProtoMessage()    {}
func (*MsgCrossVMCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8b58efff393ae7e, []int{0}
}
func (m *MsgCrossVMCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCrossVMCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCrossVMCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCrossVMCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCrossVMCall.Merge(m, src)
}
func (m *MsgCrossVMCall) XXX_Size() int {
	return m.Size()
}
func (m *MsgCrossVMCall) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCrossVMCall.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCrossVMCall proto.InternalMessageInfo

func (m *MsgCrossVMCall) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCrossVMCall) GetSourceVM() VMType {
	if m != nil {
		return m.SourceVM
	}
	return ""
}

func (m *MsgCrossVMCall) GetTargetVM() VMType {
	if m != nil {
		return m.TargetVM
	}
	return ""
}

func (m *MsgCrossVMCall) GetTargetContract() string {
	if m != nil {
		return m.TargetContract
	}
	return ""
}

func (m *MsgCrossVMCall) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgCrossVMCall) GetFunds() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Funds
	}
	return nil
}

type MsgCrossVMCallResponse struct {
	MessageID string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (m *MsgCrossVMCallResponse) Reset()         { *m = MsgCrossVMCallResponse{} }
func (m *MsgCrossVMCallResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCrossVMCallResponse) ProtoMessage()    {}
func (*MsgCrossVMCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8b58efff393ae7e, []int{1}
}
func (m *MsgCrossVMCallResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCrossVMCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCrossVMCallResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCrossVMCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCrossVMCallResponse.Merge(m, src)
}
func (m *MsgCrossVMCallResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCrossVMCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCrossVMCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCrossVMCallResponse proto.InternalMessageInfo

func (m *MsgCrossVMCallResponse) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

type MsgProcessQueue struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgProcessQueue) Reset()         { *m = MsgProcessQueue{} }
func (m *MsgProcessQueue) String() string { return proto.CompactTextString(m) }
func (*MsgProcessQueue) ProtoMessage()    {}
func (*MsgProcessQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8b58efff393ae7e, []int{2}
}
func (m *MsgProcessQueue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProcessQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProcessQueue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProcessQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProcessQueue.Merge(m, src)
}
func (m *MsgProcessQueue) XXX_Size() int {
	return m.Size()
}
func (m *MsgProcessQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProcessQueue.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProcessQueue proto.InternalMessageInfo

func (m *MsgProcessQueue) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgProcessQueueResponse struct {
}

func (m *MsgProcessQueueResponse) Reset()         { *m = MsgProcessQueueResponse{} }
func (m *MsgProcessQueueResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProcessQueueResponse) ProtoMessage()    {}
func (*MsgProcessQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8b58efff393ae7e, []int{3}
}
func (m *MsgProcessQueueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProcessQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProcessQueueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProcessQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProcessQueueResponse.Merge(m, src)
}
func (m *MsgProcessQueueResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgProcessQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProcessQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProcessQueueResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCrossVMCall)(nil), "qorechain.crossvm.v1.MsgCrossVMCall")
	proto.RegisterType((*MsgCrossVMCallResponse)(nil), "qorechain.crossvm.v1.MsgCrossVMCallResponse")
	proto.RegisterType((*MsgProcessQueue)(nil), "qorechain.crossvm.v1.MsgProcessQueue")
	proto.RegisterType((*MsgProcessQueueResponse)(nil), "qorechain.crossvm.v1.MsgProcessQueueResponse")
}

func init() { proto.RegisterFile("qorechain/crossvm/v1/tx.proto", fileDescriptor_d8b58efff393ae7e) }

var fileDescriptor_d8b58efff393ae7e = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xb6, 0xe2, 0xda, 0x8d, 0xd7, 0xa9, 0x03, 0xc2, 0x24, 0xb2, 0xa1, 0xb2, 0x31, 0x2d, 0x35,
	0x21, 0x96, 0xe2, 0x18, 0x7a, 0xc8, 0xad, 0x76, 0x29, 0xe4, 0x20, 0x68, 0x95, 0x60, 0x68, 0x2f,
	0x66, 0x2d, 0x6d, 0xd7, 0xa2, 0x96, 0xd6, 0xdd, 0x59, 0x99, 0xf8, 0x56, 0xfa, 0x04, 0x7d, 0x8e,
	0x9e, 0x72, 0xe8, 0x43, 0xe4, 0x18, 0x0a, 0x85, 0x9e, 0x9c, 0x62, 0x1f, 0xf2, 0x0e, 0x3d, 0x15,
	0x49, 0xeb, 0xbf, 0xd2, 0x92, 0x9c, 0xa4, 0xf9, 0xe6, 0xfb, 0x76, 0x76, 0xbe, 0xd9, 0x41, 0x8f,
	0x3f, 0x32, 0x4e, 0x9c, 0x01, 0xf6, 0x02, 0xd3, 0xe1, 0x0c, 0x60, 0xec, 0x9b, 0xe3, 0xa6, 0x29,
	0x2e, 0x8c, 0x11, 0x67, 0x82, 0xa9, 0xc5, 0x65, 0xda, 0x90, 0x69, 0x63, 0xdc, 0x2c, 0xef, 0x3b,
	0x0c, 0x7c, 0x06, 0xa6, 0x0f, 0x34, 0x62, 0xfb, 0x40, 0x13, 0x7a, 0xb9, 0x94, 0x24, 0x7a, 0x71,
	0x64, 0x26, 0x81, 0x4c, 0xe9, 0x52, 0xd3, 0xc7, 0x40, 0xcc, 0x71, 0xb3, 0x4f, 0x04, 0x6e, 0x9a,
	0x0e, 0xf3, 0x02, 0x99, 0x2f, 0x52, 0x46, 0x59, 0xa2, 0x8b, 0xfe, 0x12, 0xb4, 0x76, 0xb3, 0x85,
	0x0a, 0x16, 0xd0, 0x4e, 0x54, 0xbb, 0x6b, 0x75, 0xf0, 0x70, 0xa8, 0x1e, 0xa1, 0x2c, 0x90, 0xc0,
	0x25, 0x5c, 0x53, 0xaa, 0x4a, 0x3d, 0xd7, 0xd6, 0xbe, 0x7f, 0x6b, 0x14, 0x65, 0xa9, 0x17, 0xae,
	0xcb, 0x09, 0xc0, 0x99, 0xe0, 0x5e, 0x40, 0x6d, 0xc9, 0x53, 0x5b, 0x28, 0x07, 0x2c, 0xe4, 0x0e,
	0xe9, 0x8d, 0x7d, 0x6d, 0x2b, 0x16, 0xed, 0xcd, 0xa6, 0x95, 0xed, 0xb3, 0x18, 0xec, 0x5a, 0xbf,
	0xa7, 0x95, 0x6c, 0xd7, 0x3a, 0x9f, 0x8c, 0x88, 0xbd, 0x9d, 0x10, 0xbb, 0x7e, 0x24, 0x12, 0x98,
	0x53, 0x22, 0x22, 0x51, 0x7a, 0x25, 0x3a, 0x8f, 0xc1, 0x4d, 0x51, 0x42, 0xec, 0xfa, 0xea, 0x33,
	0xb4, 0x2b, 0x45, 0x0e, 0x0b, 0x04, 0xc7, 0x8e, 0xd0, 0x1e, 0x44, 0x52, 0xbb, 0x90, 0xc0, 0x1d,
	0x89, 0xaa, 0x1a, 0x7a, 0x38, 0xc2, 0x93, 0x21, 0xc3, 0xae, 0x96, 0xa9, 0x2a, 0xf5, 0x1d, 0x7b,
	0x11, 0xaa, 0x18, 0x65, 0xde, 0x87, 0x81, 0x0b, 0x5a, 0xb6, 0x9a, 0xae, 0xe7, 0x8f, 0x4b, 0x86,
	0x6c, 0x2d, 0xf2, 0xcd, 0x90, 0xbe, 0x19, 0x1d, 0xe6, 0x05, 0xed, 0xa3, 0xab, 0x69, 0x25, 0xf5,
	0xf5, 0xa6, 0x52, 0xa7, 0x9e, 0x18, 0x84, 0x7d, 0xc3, 0x61, 0xbe, 0xb4, 0x5c, 0x7e, 0x1a, 0xe0,
	0x7e, 0x30, 0xc5, 0x64, 0x44, 0x20, 0x16, 0x80, 0x9d, 0x9c, 0x7c, 0x92, 0xff, 0x7c, 0x7b, 0x79,
	0x20, 0xcd, 0xa9, 0xbd, 0x42, 0x7b, 0x9b, 0x06, 0xdb, 0x04, 0x46, 0x2c, 0x00, 0xa2, 0x1e, 0x22,
	0xe4, 0x13, 0x00, 0x4c, 0x49, 0xcf, 0x73, 0xa5, 0xd9, 0x8f, 0x66, 0xd3, 0x4a, 0xce, 0x4a, 0xd0,
	0xd3, 0x97, 0x76, 0x4e, 0x12, 0x4e, 0xdd, 0xda, 0x5b, 0xb4, 0x6b, 0x01, 0x7d, 0xcd, 0x99, 0x43,
	0x00, 0xde, 0x84, 0x24, 0x24, 0xea, 0x73, 0x94, 0xc3, 0xa1, 0x18, 0x30, 0xee, 0x89, 0xc9, 0x9d,
	0xc3, 0x5a, 0x51, 0x4f, 0x0a, 0xd1, 0xfd, 0x56, 0x71, 0xad, 0x84, 0xf6, 0xff, 0x3a, 0x7a, 0x71,
	0xc7, 0xe3, 0x1f, 0x0a, 0x4a, 0x5b, 0x40, 0x55, 0x8c, 0xf2, 0xeb, 0x6f, 0xe4, 0x89, 0xf1, 0xaf,
	0x77, 0x6b, 0x6c, 0x36, 0x5a, 0x3e, 0xbc, 0x0f, 0x6b, 0x69, 0x87, 0x8b, 0x76, 0x36, 0xba, 0x7b,
	0xfa, 0x5f, 0xf5, 0x3a, 0xad, 0xdc, 0xb8, 0x17, 0x6d, 0x51, 0xa5, 0x9c, 0xf9, 0x74, 0x7b, 0x79,
	0xa0, 0xb4, 0xad, 0xab, 0x99, 0xae, 0x5c, 0xcf, 0x74, 0xe5, 0xd7, 0x4c, 0x57, 0xbe, 0xcc, 0xf5,
	0xd4, 0xf5, 0x5c, 0x4f, 0xfd, 0x9c, 0xeb, 0xa9, 0x77, 0xad, 0xb5, 0x69, 0xaf, 0x76, 0x77, 0xf9,
	0xd7, 0x70, 0x18, 0x27, 0xe6, 0xc5, 0x72, 0x99, 0xe3, 0xf1, 0xf7, 0xb3, 0xf1, 0x36, 0xb5, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x96, 0x40, 0x55, 0xa0, 0xee, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CrossVMCall submits a cross-VM message to the queue.
	CrossVMCall(ctx context.Context, in *MsgCrossVMCall, opts ...grpc.CallOption) (*MsgCrossVMCallResponse, error)
	// ProcessQueue processes the pending cross-VM message queue.
	ProcessQueue(ctx context.Context, in *MsgProcessQueue, opts ...grpc.CallOption) (*MsgProcessQueueResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CrossVMCall(ctx context.Context, in *MsgCrossVMCall, opts ...grpc.CallOption) (*MsgCrossVMCallResponse, error) {
	out := new(MsgCrossVMCallResponse)
	err := c.cc.Invoke(ctx, "/qorechain.crossvm.v1.Msg/CrossVMCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProcessQueue(ctx context.Context, in *MsgProcessQueue, opts ...grpc.CallOption) (*MsgProcessQueueResponse, error) {
	out := new(MsgProcessQueueResponse)
	err := c.cc.Invoke(ctx, "/qorechain.crossvm.v1.Msg/ProcessQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CrossVMCall submits a cross-VM message to the queue.
	CrossVMCall(context.Context, *MsgCrossVMCall) (*MsgCrossVMCallResponse, error)
	// ProcessQueue processes the pending cross-VM message queue.
	ProcessQueue(context.Context, *MsgProcessQueue) (*MsgProcessQueueResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CrossVMCall(ctx context.Context, req *MsgCrossVMCall) (*MsgCrossVMCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrossVMCall not implemented")
}
func (*UnimplementedMsgServer) ProcessQueue(ctx context.Context, req *MsgProcessQueue) (*MsgProcessQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessQueue not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CrossVMCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCrossVMCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CrossVMCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.crossvm.v1.Msg/CrossVMCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CrossVMCall(ctx, req.(*MsgCrossVMCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProcessQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProcessQueue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProcessQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.crossvm.v1.Msg/ProcessQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProcessQueue(ctx, req.(*MsgProcessQueue))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.crossvm.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrossVMCall",
			Handler:    _Msg_CrossVMCall_Handler,
		},
		{
			MethodName: "ProcessQueue",
			Handler:    _Msg_ProcessQueue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/crossvm/v1/tx.proto",
}

func (m *MsgCrossVMCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCrossVMCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCrossVMCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Funds) > 0 {
		for iNdEx := len(m.Funds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Funds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TargetContract) > 0 {
		i -= len(m.TargetContract)
		copy(dAtA[i:], m.TargetContract)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetContract)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TargetVM) > 0 {
		i -= len(m.TargetVM)
		copy(dAtA[i:], m.TargetVM)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetVM)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SourceVM) > 0 {
		i -= len(m.SourceVM)
		copy(dAtA[i:], m.SourceVM)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceVM)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCrossVMCallResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCrossVMCallResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCrossVMCallResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageID) > 0 {
		i -= len(m.MessageID)
		copy(dAtA[i:], m.MessageID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MessageID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProcessQueue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProcessQueue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProcessQueue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProcessQueueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProcessQueueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProcessQueueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCrossVMCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceVM)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetVM)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetContract)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Funds) > 0 {
		for _, e := range m.Funds {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCrossVMCallResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MessageID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgProcessQueue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgProcessQueueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCrossVMCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCrossVMCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCrossVMCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceVM", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceVM = VMType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetVM", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetVM = VMType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetContract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetContract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funds = append(m.Funds, types.Coin{})
			if err := m.Funds[len(m.Funds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCrossVMCallResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCrossVMCallResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCrossVMCallResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProcessQueue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProcessQueue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProcessQueue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProcessQueueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProcessQueueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProcessQueueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
