// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/qca/v1/query.proto

package types

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryConfigRequest struct {
}

func (m *QueryConfigRequest) Reset()         { *m = QueryConfigRequest{} }
func (m *QueryConfigRequest) String() string { return proto.CompactTextString(m) }
func (*QueryConfigRequest) ProtoMessage()    {}
func (*QueryConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3f21644713369f, []int{0}
}
func (m *QueryConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConfigRequest.Merge(m, src)
}
func (m *QueryConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConfigRequest proto.InternalMessageInfo

type QueryConfigResponse struct {
	UseReputationWeighting bool    `protobuf:"varint,1,opt,name=use_reputation_weighting,json=useReputationWeighting,proto3" json:"use_reputation_weighting,omitempty"`
	MinReputationScore     float64 `protobuf:"fixed64,2,opt,name=min_reputation_score,json=minReputationScore,proto3" json:"min_reputation_score,omitempty"`
	// PoolConfig
	PoolClassificationInterval uint64 `protobuf:"varint,3,opt,name=pool_classification_interval,json=poolClassificationInterval,proto3" json:"pool_classification_interval,omitempty"`
	PoolWeightRpos             string `protobuf:"bytes,4,opt,name=pool_weight_rpos,json=poolWeightRpos,proto3" json:"pool_weight_rpos,omitempty"`
	PoolWeightDpos             string `protobuf:"bytes,5,opt,name=pool_weight_dpos,json=poolWeightDpos,proto3" json:"pool_weight_dpos,omitempty"`
	PoolMinDelegationDpos      uint64 `protobuf:"varint,6,opt,name=pool_min_delegation_dpos,json=poolMinDelegationDpos,proto3" json:"pool_min_delegation_dpos,omitempty"`
	PoolRepPercentileRpos      uint64 `protobuf:"varint,7,opt,name=pool_rep_percentile_rpos,json=poolRepPercentileRpos,proto3" json:"pool_rep_percentile_rpos,omitempty"`
	// BondingCurveConfig
	BondingAlpha           string `protobuf:"bytes,8,opt,name=bonding_alpha,json=bondingAlpha,proto3" json:"bonding_alpha,omitempty"`
	BondingBeta            string `protobuf:"bytes,9,opt,name=bonding_beta,json=bondingBeta,proto3" json:"bonding_beta,omitempty"`
	BondingPhaseMultiplier string `protobuf:"bytes,10,opt,name=bonding_phase_multiplier,json=bondingPhaseMultiplier,proto3" json:"bonding_phase_multiplier,omitempty"`
	// SlashingConfig
	SlashingBaseRate         string `protobuf:"bytes,11,opt,name=slashing_base_rate,json=slashingBaseRate,proto3" json:"slashing_base_rate,omitempty"`
	SlashingEscalationFactor string `protobuf:"bytes,12,opt,name=slashing_escalation_factor,json=slashingEscalationFactor,proto3" json:"slashing_escalation_factor,omitempty"`
	SlashingMaxPenalty       string `protobuf:"bytes,13,opt,name=slashing_max_penalty,json=slashingMaxPenalty,proto3" json:"slashing_max_penalty,omitempty"`
	SlashingDecayHalflife    uint64 `protobuf:"varint,14,opt,name=slashing_decay_halflife,json=slashingDecayHalflife,proto3" json:"slashing_decay_halflife,omitempty"`
	// QDRWConfig
	QdrwEnabled          bool   `protobuf:"varint,15,opt,name=qdrw_enabled,json=qdrwEnabled,proto3" json:"qdrw_enabled,omitempty"`
	QdrwXqoreMultiplier  string `protobuf:"bytes,16,opt,name=qdrw_xqore_multiplier,json=qdrwXqoreMultiplier,proto3" json:"qdrw_xqore_multiplier,omitempty"`
	QdrwRepMinMultiplier string `protobuf:"bytes,17,opt,name=qdrw_rep_min_multiplier,json=qdrwRepMinMultiplier,proto3" json:"qdrw_rep_min_multiplier,omitempty"`
	QdrwRepMaxMultiplier string `protobuf:"bytes,18,opt,name=qdrw_rep_max_multiplier,json=qdrwRepMaxMultiplier,proto3" json:"qdrw_rep_max_multiplier,omitempty"`
}

func (m *QueryConfigResponse) Reset()         { *m = QueryConfigResponse{} }
func (m *QueryConfigResponse) String() string { return proto.CompactTextString(m) }
func (*QueryConfigResponse) ProtoMessage()    {}
func (*QueryConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd3f21644713369f, []int{1}
}
func (m *QueryConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConfigResponse.Merge(m, src)
}
func (m *QueryConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConfigResponse proto.InternalMessageInfo

func (m *QueryConfigResponse) GetUseReputationWeighting() bool {
	if m != nil {
		return m.UseReputationWeighting
	}
	return false
}

func (m *QueryConfigResponse) GetMinReputationScore() float64 {
	if m != nil {
		return m.MinReputationScore
	}
	return 0
}

func (m *QueryConfigResponse) GetPoolClassificationInterval() uint64 {
	if m != nil {
		return m.PoolClassificationInterval
	}
	return 0
}

func (m *QueryConfigResponse) GetPoolWeightRpos() string {
	if m != nil {
		return m.PoolWeightRpos
	}
	return ""
}

func (m *QueryConfigResponse) GetPoolWeightDpos() string {
	if m != nil {
		return m.PoolWeightDpos
	}
	return ""
}

func (m *QueryConfigResponse) GetPoolMinDelegationDpos() uint64 {
	if m != nil {
		return m.PoolMinDelegationDpos
	}
	return 0
}

func (m *QueryConfigResponse) GetPoolRepPercentileRpos() uint64 {
	if m != nil {
		return m.PoolRepPercentileRpos
	}
	return 0
}

func (m *QueryConfigResponse) GetBondingAlpha() string {
	if m != nil {
		return m.BondingAlpha
	}
	return ""
}

func (m *QueryConfigResponse) GetBondingBeta() string {
	if m != nil {
		return m.BondingBeta
	}
	return ""
}

func (m *QueryConfigResponse) GetBondingPhaseMultiplier() string {
	if m != nil {
		return m.BondingPhaseMultiplier
	}
	return ""
}

func (m *QueryConfigResponse) GetSlashingBaseRate() string {
	if m != nil {
		return m.SlashingBaseRate
	}
	return ""
}

func (m *QueryConfigResponse) GetSlashingEscalationFactor() string {
	if m != nil {
		return m.SlashingEscalationFactor
	}
	return ""
}

func (m *QueryConfigResponse) GetSlashingMaxPenalty() string {
	if m != nil {
		return m.SlashingMaxPenalty
	}
	return ""
}

func (m *QueryConfigResponse) GetSlashingDecayHalflife() uint64 {
	if m != nil {
		return m.SlashingDecayHalflife
	}
	return 0
}

func (m *QueryConfigResponse) GetQdrwEnabled() bool {
	if m != nil {
		return m.QdrwEnabled
	}
	return false
}

func (m *QueryConfigResponse) GetQdrwXqoreMultiplier() string {
	if m != nil {
		return m.QdrwXqoreMultiplier
	}
	return ""
}

func (m *QueryConfigResponse) GetQdrwRepMinMultiplier() string {
	if m != nil {
		return m.QdrwRepMinMultiplier
	}
	return ""
}

func (m *QueryConfigResponse) GetQdrwRepMaxMultiplier() string {
	if m != nil {
		return m.QdrwRepMaxMultiplier
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryConfigRequest)(nil), "qorechain.qca.v1.QueryConfigRequest")
	proto.RegisterType((*QueryConfigResponse)(nil), "qorechain.qca.v1.QueryConfigResponse")
}

func init() { proto.RegisterFile("qorechain/qca/v1/query.proto", fileDescriptor_bd3f21644713369f) }

var fileDescriptor_bd3f21644713369f = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcb, 0x6e, 0x13, 0x3d,
	0x14, 0xc7, 0x3b, 0xdf, 0xd7, 0xab, 0x7b, 0x21, 0xb8, 0x37, 0xab, 0xaa, 0xa2, 0x50, 0x40, 0xca,
	0x02, 0x12, 0x5a, 0xc4, 0x65, 0xc1, 0x02, 0x7a, 0x41, 0x74, 0x11, 0xa9, 0x0c, 0x42, 0x20, 0x16,
	0x8c, 0x4e, 0x26, 0x27, 0x19, 0x4b, 0x8e, 0xed, 0x8c, 0x3d, 0x6d, 0xf2, 0x16, 0x3c, 0x05, 0xcf,
	0xc2, 0xb2, 0x4b, 0x96, 0xa8, 0x7d, 0x11, 0x64, 0x4f, 0x66, 0x9a, 0x14, 0x21, 0x76, 0xc9, 0xf9,
	0xfd, 0x7f, 0xa3, 0x33, 0x67, 0x7c, 0x4c, 0x76, 0x07, 0x2a, 0xc5, 0x38, 0x01, 0x2e, 0x9b, 0x83,
	0x18, 0x9a, 0xe7, 0xfb, 0xcd, 0x41, 0x86, 0xe9, 0xa8, 0xa1, 0x53, 0x65, 0x15, 0xad, 0x94, 0xb4,
	0x31, 0x88, 0xa1, 0x71, 0xbe, 0xbf, 0xb7, 0x41, 0xe8, 0x7b, 0x17, 0x38, 0x52, 0xb2, 0xcb, 0x7b,
	0x21, 0x0e, 0x32, 0x34, 0x76, 0xef, 0xfb, 0x02, 0x59, 0x9f, 0x2a, 0x1b, 0xad, 0xa4, 0x41, 0xfa,
	0x92, 0xb0, 0xcc, 0x60, 0x94, 0xa2, 0xce, 0x2c, 0x58, 0xae, 0x64, 0x74, 0x81, 0xbc, 0x97, 0x58,
	0x2e, 0x7b, 0x2c, 0xa8, 0x05, 0xf5, 0xc5, 0x70, 0x2b, 0x33, 0x18, 0x96, 0xf8, 0x53, 0x41, 0xe9,
	0x13, 0xb2, 0xd1, 0xe7, 0x72, 0xd2, 0x34, 0xb1, 0x4a, 0x91, 0xfd, 0x57, 0x0b, 0xea, 0x41, 0x48,
	0xfb, 0x5c, 0xde, 0x58, 0x1f, 0x1c, 0xa1, 0xaf, 0xc9, 0xae, 0x56, 0x4a, 0x44, 0xb1, 0x00, 0x63,
	0x78, 0x97, 0xc7, 0xb9, 0xc6, 0xa5, 0xc5, 0xf4, 0x1c, 0x04, 0xfb, 0xbf, 0x16, 0xd4, 0x67, 0xc3,
	0x1d, 0x97, 0x39, 0x9a, 0x8a, 0x9c, 0x8e, 0x13, 0xb4, 0x4e, 0x2a, 0xfe, 0x09, 0x79, 0x8f, 0x51,
	0xaa, 0x95, 0x61, 0xb3, 0xb5, 0xa0, 0xbe, 0x14, 0xae, 0xb9, 0x7a, 0xde, 0x5c, 0xa8, 0x95, 0xb9,
	0x9d, 0xec, 0xb8, 0xe4, 0xdc, 0xed, 0xe4, 0xb1, 0x4b, 0xbe, 0x20, 0xcc, 0x27, 0xdd, 0xcb, 0x74,
	0x50, 0x60, 0x2f, 0xef, 0xca, 0x1b, 0xf3, 0xbe, 0xa3, 0x4d, 0xc7, 0x5b, 0x5c, 0x1e, 0x97, 0x74,
	0x4a, 0x4c, 0x51, 0x47, 0x1a, 0xd3, 0x18, 0xa5, 0xe5, 0x02, 0xf3, 0xa6, 0x16, 0x6e, 0xc4, 0x10,
	0xf5, 0x59, 0x49, 0x7d, 0x6f, 0xf7, 0xc9, 0x6a, 0x5b, 0xc9, 0x0e, 0x97, 0xbd, 0x08, 0x84, 0x4e,
	0x80, 0x2d, 0xfa, 0xc6, 0x56, 0xc6, 0xc5, 0x37, 0xae, 0x46, 0xef, 0x91, 0xe2, 0x7f, 0xd4, 0x46,
	0x0b, 0x6c, 0xc9, 0x67, 0x96, 0xc7, 0xb5, 0x43, 0xb4, 0xe0, 0xbe, 0x5d, 0x11, 0xd1, 0x09, 0x18,
	0x8c, 0xfa, 0x99, 0xb0, 0x5c, 0x0b, 0x8e, 0x29, 0x23, 0x3e, 0xbe, 0x35, 0xe6, 0x67, 0x0e, 0xb7,
	0x4a, 0x4a, 0x1f, 0x11, 0x6a, 0x04, 0x98, 0xc4, 0x3f, 0xdd, 0x99, 0x29, 0x58, 0x64, 0xcb, 0xde,
	0xa9, 0x14, 0xe4, 0x10, 0x0c, 0x86, 0x60, 0x91, 0xbe, 0x22, 0x3b, 0x65, 0x1a, 0x4d, 0x0c, 0x22,
	0x9f, 0x50, 0x17, 0x62, 0xab, 0x52, 0xb6, 0xe2, 0x2d, 0x56, 0x24, 0x4e, 0xca, 0xc0, 0x5b, 0xcf,
	0xdd, 0x39, 0x29, 0xed, 0x3e, 0x0c, 0x23, 0x8d, 0x12, 0x84, 0x1d, 0xb1, 0x55, 0xef, 0x95, 0x7d,
	0xb4, 0x60, 0x78, 0x96, 0x13, 0xfa, 0x9c, 0x6c, 0x97, 0x46, 0x07, 0x63, 0x18, 0x45, 0x09, 0x88,
	0xae, 0xe0, 0x5d, 0x64, 0x6b, 0xf9, 0x5c, 0x0b, 0x7c, 0xec, 0xe8, 0xbb, 0x31, 0x74, 0x23, 0x1b,
	0x74, 0xd2, 0x8b, 0x08, 0x25, 0xb4, 0x05, 0x76, 0xd8, 0x1d, 0x7f, 0x7e, 0x97, 0x5d, 0xed, 0x24,
	0x2f, 0xd1, 0x03, 0xb2, 0xe9, 0x23, 0x43, 0xb7, 0x36, 0x93, 0xf3, 0xaa, 0xf8, 0x6e, 0xd6, 0x1d,
	0xfc, 0xec, 0xd8, 0xc4, 0xb0, 0x9e, 0x91, 0x6d, 0xef, 0xb8, 0xef, 0xec, 0x0e, 0xc9, 0x84, 0x75,
	0xd7, 0x5b, 0x1b, 0x0e, 0x87, 0xa8, 0x5b, 0x5c, 0xfe, 0x4d, 0x83, 0xe1, 0xa4, 0x46, 0xa7, 0x35,
	0x18, 0xde, 0x68, 0x07, 0x5f, 0xc9, 0x9c, 0xdf, 0x53, 0xfa, 0x91, 0xcc, 0xe7, 0xbb, 0x4a, 0x1f,
	0x34, 0x6e, 0x2f, 0x79, 0xe3, 0xcf, 0x0d, 0xdf, 0x79, 0xf8, 0x8f, 0x54, 0xbe, 0xf0, 0x87, 0xa7,
	0x3f, 0xae, 0xaa, 0xc1, 0xe5, 0x55, 0x35, 0xf8, 0x75, 0x55, 0x0d, 0xbe, 0x5d, 0x57, 0x67, 0x2e,
	0xaf, 0xab, 0x33, 0x3f, 0xaf, 0xab, 0x33, 0x5f, 0x9a, 0x3d, 0x6e, 0x93, 0xac, 0xdd, 0x88, 0x55,
	0xbf, 0x39, 0x71, 0xe7, 0x14, 0xbf, 0x1e, 0xbb, 0x1d, 0x6e, 0x0e, 0xfd, 0x25, 0x64, 0x47, 0x1a,
	0x4d, 0x7b, 0xde, 0x5f, 0x41, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x98, 0xa7, 0xe0, 0x0d,
	0xa2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Config returns the live QCA consensus configuration (pool, bonding curve,
	// slashing and QDRW sub-configs flattened).
	Config(ctx context.Context, in *QueryConfigRequest, opts ...grpc.CallOption) (*QueryConfigResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Config(ctx context.Context, in *QueryConfigRequest, opts ...grpc.CallOption) (*QueryConfigResponse, error) {
	out := new(QueryConfigResponse)
	err := c.cc.Invoke(ctx, "/qorechain.qca.v1.Query/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Config returns the live QCA consensus configuration (pool, bonding curve,
	// slashing and QDRW sub-configs flattened).
	Config(context.Context, *QueryConfigRequest) (*QueryConfigResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Config(ctx context.Context, req *QueryConfigRequest) (*QueryConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.qca.v1.Query/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Config(ctx, req.(*QueryConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.qca.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _Query_Config_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/qca/v1/query.proto",
}

func (m *QueryConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QdrwRepMaxMultiplier) > 0 {
		i -= len(m.QdrwRepMaxMultiplier)
		copy(dAtA[i:], m.QdrwRepMaxMultiplier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QdrwRepMaxMultiplier)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.QdrwRepMinMultiplier) > 0 {
		i -= len(m.QdrwRepMinMultiplier)
		copy(dAtA[i:], m.QdrwRepMinMultiplier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QdrwRepMinMultiplier)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.QdrwXqoreMultiplier) > 0 {
		i -= len(m.QdrwXqoreMultiplier)
		copy(dAtA[i:], m.QdrwXqoreMultiplier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QdrwXqoreMultiplier)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.QdrwEnabled {
		i--
		if m.QdrwEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.SlashingDecayHalflife != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SlashingDecayHalflife))
		i--
		dAtA[i] = 0x70
	}
	if len(m.SlashingMaxPenalty) > 0 {
		i -= len(m.SlashingMaxPenalty)
		copy(dAtA[i:], m.SlashingMaxPenalty)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SlashingMaxPenalty)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.SlashingEscalationFactor) > 0 {
		i -= len(m.SlashingEscalationFactor)
		copy(dAtA[i:], m.SlashingEscalationFactor)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SlashingEscalationFactor)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.SlashingBaseRate) > 0 {
		i -= len(m.SlashingBaseRate)
		copy(dAtA[i:], m.SlashingBaseRate)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SlashingBaseRate)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.BondingPhaseMultiplier) > 0 {
		i -= len(m.BondingPhaseMultiplier)
		copy(dAtA[i:], m.BondingPhaseMultiplier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BondingPhaseMultiplier)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.BondingBeta) > 0 {
		i -= len(m.BondingBeta)
		copy(dAtA[i:], m.BondingBeta)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BondingBeta)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.BondingAlpha) > 0 {
		i -= len(m.BondingAlpha)
		copy(dAtA[i:], m.BondingAlpha)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BondingAlpha)))
		i--
		dAtA[i] = 0x42
	}
	if m.PoolRepPercentileRpos != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolRepPercentileRpos))
		i--
		dAtA[i] = 0x38
	}
	if m.PoolMinDelegationDpos != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolMinDelegationDpos))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PoolWeightDpos) > 0 {
		i -= len(m.PoolWeightDpos)
		copy(dAtA[i:], m.PoolWeightDpos)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PoolWeightDpos)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PoolWeightRpos) > 0 {
		i -= len(m.PoolWeightRpos)
		copy(dAtA[i:], m.PoolWeightRpos)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PoolWeightRpos)))
		i--
		dAtA[i] = 0x22
	}
	if m.PoolClassificationInterval != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolClassificationInterval))
		i--
		dAtA[i] = 0x18
	}
	if m.MinReputationScore != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.MinReputationScore))))
		i--
		dAtA[i] = 0x11
	}
	if m.UseReputationWeighting {
		i--
		if m.UseReputationWeighting {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UseReputationWeighting {
		n += 2
	}
	if m.MinReputationScore != 0 {
		n += 9
	}
	if m.PoolClassificationInterval != 0 {
		n += 1 + sovQuery(uint64(m.PoolClassificationInterval))
	}
	l = len(m.PoolWeightRpos)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PoolWeightDpos)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.PoolMinDelegationDpos != 0 {
		n += 1 + sovQuery(uint64(m.PoolMinDelegationDpos))
	}
	if m.PoolRepPercentileRpos != 0 {
		n += 1 + sovQuery(uint64(m.PoolRepPercentileRpos))
	}
	l = len(m.BondingAlpha)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BondingBeta)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BondingPhaseMultiplier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SlashingBaseRate)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SlashingEscalationFactor)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SlashingMaxPenalty)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.SlashingDecayHalflife != 0 {
		n += 1 + sovQuery(uint64(m.SlashingDecayHalflife))
	}
	if m.QdrwEnabled {
		n += 2
	}
	l = len(m.QdrwXqoreMultiplier)
	if l > 0 {
		n += 2 + l + sovQuery(uint64(l))
	}
	l = len(m.QdrwRepMinMultiplier)
	if l > 0 {
		n += 2 + l + sovQuery(uint64(l))
	}
	l = len(m.QdrwRepMaxMultiplier)
	if l > 0 {
		n += 2 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UseReputationWeighting", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UseReputationWeighting = bool(v != 0)
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReputationScore", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.MinReputationScore = float64(math.Float64frombits(v))
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolClassificationInterval", wireType)
			}
			m.PoolClassificationInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolClassificationInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolWeightRpos", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolWeightRpos = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolWeightDpos", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolWeightDpos = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolMinDelegationDpos", wireType)
			}
			m.PoolMinDelegationDpos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolMinDelegationDpos |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolRepPercentileRpos", wireType)
			}
			m.PoolRepPercentileRpos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolRepPercentileRpos |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingAlpha", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingAlpha = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingBeta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingBeta = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingPhaseMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingPhaseMultiplier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashingBaseRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashingBaseRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashingEscalationFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashingEscalationFactor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashingMaxPenalty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashingMaxPenalty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashingDecayHalflife", wireType)
			}
			m.SlashingDecayHalflife = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashingDecayHalflife |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QdrwEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.QdrwEnabled = bool(v != 0)
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QdrwXqoreMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QdrwXqoreMultiplier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QdrwRepMinMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QdrwRepMinMultiplier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QdrwRepMaxMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QdrwRepMaxMultiplier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
