// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/rdk/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateRollup struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	RollupID    string `protobuf:"bytes,2,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	Profile     string `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	VmType      string `protobuf:"bytes,4,opt,name=vm_type,json=vmType,proto3" json:"vm_type,omitempty"`
	StakeAmount int64  `protobuf:"varint,5,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`
}

func (m *MsgCreateRollup) Reset()         { *m = MsgCreateRollup{} }
func (m *MsgCreateRollup) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRollup) ProtoMessage()    {}
func (*MsgCreateRollup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{0}
}
func (m *MsgCreateRollup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRollup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRollup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRollup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRollup.Merge(m, src)
}
func (m *MsgCreateRollup) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRollup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRollup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRollup proto.InternalMessageInfo

func (m *MsgCreateRollup) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateRollup) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

func (m *MsgCreateRollup) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *MsgCreateRollup) GetVmType() string {
	if m != nil {
		return m.VmType
	}
	return ""
}

func (m *MsgCreateRollup) GetStakeAmount() int64 {
	if m != nil {
		return m.StakeAmount
	}
	return 0
}

type MsgCreateRollupResponse struct {
	RollupID string `protobuf:"bytes,1,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
}

func (m *MsgCreateRollupResponse) Reset()         { *m = MsgCreateRollupResponse{} }
func (m *MsgCreateRollupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRollupResponse) ProtoMessage()    {}
func (*MsgCreateRollupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{1}
}
func (m *MsgCreateRollupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRollupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRollupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRollupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRollupResponse.Merge(m, src)
}
func (m *MsgCreateRollupResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRollupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRollupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRollupResponse proto.InternalMessageInfo

func (m *MsgCreateRollupResponse) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

type MsgSubmitBatch struct {
	Sequencer     string `protobuf:"bytes,1,opt,name=sequencer,proto3" json:"sequencer,omitempty"`
	RollupID      string `protobuf:"bytes,2,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	BatchIndex    uint64 `protobuf:"varint,3,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	StateRoot     []byte `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	PrevStateRoot []byte `protobuf:"bytes,5,opt,name=prev_state_root,json=prevStateRoot,proto3" json:"prev_state_root,omitempty"`
	TxCount       uint64 `protobuf:"varint,6,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	DataHash      []byte `protobuf:"bytes,7,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Proof         []byte `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *MsgSubmitBatch) Reset()         { *m = MsgSubmitBatch{} }
func (m *MsgSubmitBatch) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBatch) ProtoMessage()    {}
func (*MsgSubmitBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{2}
}
func (m *MsgSubmitBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBatch.Merge(m, src)
}
func (m *MsgSubmitBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBatch proto.InternalMessageInfo

func (m *MsgSubmitBatch) GetSequencer() string {
	if m != nil {
		return m.Sequencer
	}
	return ""
}

func (m *MsgSubmitBatch) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

func (m *MsgSubmitBatch) GetBatchIndex() uint64 {
	if m != nil {
		return m.BatchIndex
	}
	return 0
}

func (m *MsgSubmitBatch) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *MsgSubmitBatch) GetPrevStateRoot() []byte {
	if m != nil {
		return m.PrevStateRoot
	}
	return nil
}

func (m *MsgSubmitBatch) GetTxCount() uint64 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *MsgSubmitBatch) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *MsgSubmitBatch) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type MsgSubmitBatchResponse struct {
}

func (m *MsgSubmitBatchResponse) Reset()         { *m = MsgSubmitBatchResponse{} }
func (m *MsgSubmitBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitBatchResponse) ProtoMessage()    {}
func (*MsgSubmitBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{3}
}
func (m *MsgSubmitBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitBatchResponse.Merge(m, src)
}
func (m *MsgSubmitBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitBatchResponse proto.InternalMessageInfo

type MsgChallengeBatch struct {
	Challenger string `protobuf:"bytes,1,opt,name=challenger,proto3" json:"challenger,omitempty"`
	RollupID   string `protobuf:"bytes,2,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	BatchIndex uint64 `protobuf:"varint,3,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	Proof      []byte `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *MsgChallengeBatch) Reset()         { *m = MsgChallengeBatch{} }
func (m *MsgChallengeBatch) String() string { return proto.CompactTextString(m) }
func (*MsgChallengeBatch) ProtoMessage()    {}
func (*MsgChallengeBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{4}
}
func (m *MsgChallengeBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChallengeBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChallengeBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChallengeBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChallengeBatch.Merge(m, src)
}
func (m *MsgChallengeBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgChallengeBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChallengeBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChallengeBatch proto.InternalMessageInfo

func (m *MsgChallengeBatch) GetChallenger() string {
	if m != nil {
		return m.Challenger
	}
	return ""
}

func (m *MsgChallengeBatch) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

func (m *MsgChallengeBatch) GetBatchIndex() uint64 {
	if m != nil {
		return m.BatchIndex
	}
	return 0
}

func (m *MsgChallengeBatch) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type MsgChallengeBatchResponse struct {
}

func (m *MsgChallengeBatchResponse) Reset()         { *m = MsgChallengeBatchResponse{} }
func (m *MsgChallengeBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChallengeBatchResponse) ProtoMessage()    {}
func (*MsgChallengeBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{5}
}
func (m *MsgChallengeBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChallengeBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChallengeBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChallengeBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChallengeBatchResponse.Merge(m, src)
}
func (m *MsgChallengeBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChallengeBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChallengeBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChallengeBatchResponse proto.InternalMessageInfo

type MsgPauseRollup struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	RollupID string `protobuf:"bytes,2,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
	Reason   string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgPauseRollup) Reset()         { *m = MsgPauseRollup{} }
func (m *MsgPauseRollup) String() string { return proto.CompactTextString(m) }
func (*MsgPauseRollup) ProtoMessage()    {}
func (*MsgPauseRollup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{6}
}
func (m *MsgPauseRollup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseRollup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseRollup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseRollup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseRollup.Merge(m, src)
}
func (m *MsgPauseRollup) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseRollup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseRollup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseRollup proto.InternalMessageInfo

func (m *MsgPauseRollup) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgPauseRollup) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

func (m *MsgPauseRollup) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type MsgPauseRollupResponse struct {
}

func (m *MsgPauseRollupResponse) Reset()         { *m = MsgPauseRollupResponse{} }
func (m *MsgPauseRollupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseRollupResponse) ProtoMessage()    {}
func (*MsgPauseRollupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{7}
}
func (m *MsgPauseRollupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseRollupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseRollupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseRollupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseRollupResponse.Merge(m, src)
}
func (m *MsgPauseRollupResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseRollupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseRollupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseRollupResponse proto.InternalMessageInfo

type MsgResumeRollup struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	RollupID string `protobuf:"bytes,2,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
}

func (m *MsgResumeRollup) Reset()         { *m = MsgResumeRollup{} }
func (m *MsgResumeRollup) String() string { return proto.CompactTextString(m) }
func (*MsgResumeRollup) ProtoMessage()    {}
func (*MsgResumeRollup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{8}
}
func (m *MsgResumeRollup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResumeRollup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResumeRollup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResumeRollup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResumeRollup.Merge(m, src)
}
func (m *MsgResumeRollup) XXX_Size() int {
	return m.Size()
}
func (m *MsgResumeRollup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResumeRollup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResumeRollup proto.InternalMessageInfo

func (m *MsgResumeRollup) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgResumeRollup) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

type MsgResumeRollupResponse struct {
}

func (m *MsgResumeRollupResponse) Reset()         { *m = MsgResumeRollupResponse{} }
func (m *MsgResumeRollupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResumeRollupResponse) ProtoMessage()    {}
func (*MsgResumeRollupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{9}
}
func (m *MsgResumeRollupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResumeRollupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResumeRollupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResumeRollupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResumeRollupResponse.Merge(m, src)
}
func (m *MsgResumeRollupResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgResumeRollupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResumeRollupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResumeRollupResponse proto.InternalMessageInfo

type MsgStopRollup struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	RollupID string `protobuf:"bytes,2,opt,name=rollup_id,json=rollupId,proto3" json:"rollup_id,omitempty"`
}

func (m *MsgStopRollup) Reset()         { *m = MsgStopRollup{} }
func (m *MsgStopRollup) String() string { return proto.CompactTextString(m) }
func (*MsgStopRollup) ProtoMessage()    {}
func (*MsgStopRollup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{10}
}
func (m *MsgStopRollup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStopRollup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStopRollup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStopRollup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStopRollup.Merge(m, src)
}
func (m *MsgStopRollup) XXX_Size() int {
	return m.Size()
}
func (m *MsgStopRollup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStopRollup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStopRollup proto.InternalMessageInfo

func (m *MsgStopRollup) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgStopRollup) GetRollupID() string {
	if m != nil {
		return m.RollupID
	}
	return ""
}

type MsgStopRollupResponse struct {
}

func (m *MsgStopRollupResponse) Reset()         { *m = MsgStopRollupResponse{} }
func (m *MsgStopRollupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStopRollupResponse) ProtoMessage()    {}
func (*MsgStopRollupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8226b2780a73a9c7, []int{11}
}
func (m *MsgStopRollupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStopRollupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStopRollupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStopRollupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStopRollupResponse.Merge(m, src)
}
func (m *MsgStopRollupResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStopRollupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStopRollupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStopRollupResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateRollup)(nil), "qorechain.rdk.v1.MsgCreateRollup")
	proto.RegisterType((*MsgCreateRollupResponse)(nil), "qorechain.rdk.v1.MsgCreateRollupResponse")
	proto.RegisterType((*MsgSubmitBatch)(nil), "qorechain.rdk.v1.MsgSubmitBatch")
	proto.RegisterType((*MsgSubmitBatchResponse)(nil), "qorechain.rdk.v1.MsgSubmitBatchResponse")
	proto.RegisterType((*MsgChallengeBatch)(nil), "qorechain.rdk.v1.MsgChallengeBatch")
	proto.RegisterType((*MsgChallengeBatchResponse)(nil), "qorechain.rdk.v1.MsgChallengeBatchResponse")
	proto.RegisterType((*MsgPauseRollup)(nil), "qorechain.rdk.v1.MsgPauseRollup")
	proto.RegisterType((*MsgPauseRollupResponse)(nil), "qorechain.rdk.v1.MsgPauseRollupResponse")
	proto.RegisterType((*MsgResumeRollup)(nil), "qorechain.rdk.v1.MsgResumeRollup")
	proto.RegisterType((*MsgResumeRollupResponse)(nil), "qorechain.rdk.v1.MsgResumeRollupResponse")
	proto.RegisterType((*MsgStopRollup)(nil), "qorechain.rdk.v1.MsgStopRollup")
	proto.RegisterType((*MsgStopRollupResponse)(nil), "qorechain.rdk.v1.MsgStopRollupResponse")
}

func init() { proto.RegisterFile("qorechain/rdk/v1/tx.proto", fileDescriptor_8226b2780a73a9c7) }

var fileDescriptor_8226b2780a73a9c7 = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4f, 0x6f, 0xd3, 0x4a,
	0x10, 0xaf, 0xdb, 0xfc, 0x9d, 0xa6, 0xed, 0x7b, 0x56, 0x5f, 0xe3, 0xa4, 0x7a, 0x69, 0x9b, 0x27,
	0x3d, 0xda, 0xa2, 0xc6, 0x6a, 0x91, 0x10, 0xea, 0xad, 0x7f, 0x0e, 0xe4, 0x50, 0x09, 0xb9, 0x08,
	0x09, 0x84, 0x64, 0x39, 0xf6, 0xd6, 0xb1, 0x1a, 0x7b, 0xdd, 0xdd, 0x75, 0x94, 0x4a, 0x08, 0x21,
	0x3e, 0x01, 0x17, 0xbe, 0x47, 0x0f, 0x5c, 0xe0, 0xc4, 0x91, 0x63, 0x85, 0x38, 0x70, 0x42, 0x28,
	0x3d, 0xf4, 0x6b, 0xa0, 0x5d, 0xc7, 0xae, 0x13, 0x5c, 0x02, 0x12, 0x2a, 0x37, 0xcf, 0xcc, 0x6f,
	0x77, 0x7e, 0xf3, 0xf3, 0xcc, 0xd8, 0x50, 0x39, 0xc1, 0x04, 0x99, 0x6d, 0xc3, 0xf1, 0x54, 0x62,
	0x1d, 0xab, 0xdd, 0x4d, 0x95, 0xf5, 0x1a, 0x3e, 0xc1, 0x0c, 0xcb, 0x7f, 0xc5, 0xa1, 0x06, 0xb1,
	0x8e, 0x1b, 0xdd, 0xcd, 0x6a, 0xd9, 0xc4, 0xd4, 0xc5, 0x54, 0x75, 0xa9, 0xcd, 0x91, 0x2e, 0xb5,
	0x43, 0x68, 0xb5, 0x12, 0x06, 0x74, 0x61, 0xa9, 0xa1, 0x31, 0x08, 0xcd, 0xdb, 0xd8, 0xc6, 0xa1,
	0x9f, 0x3f, 0x85, 0xde, 0xfa, 0x27, 0x09, 0xe6, 0x0e, 0xa8, 0xbd, 0x47, 0x90, 0xc1, 0x90, 0x86,
	0x3b, 0x9d, 0xc0, 0x97, 0xb7, 0x20, 0x6f, 0x72, 0x1b, 0x13, 0x45, 0x5a, 0x96, 0x56, 0x8b, 0xbb,
	0xca, 0xc7, 0x37, 0x1b, 0xf3, 0x83, 0xcb, 0x76, 0x2c, 0x8b, 0x20, 0x4a, 0x0f, 0x19, 0x71, 0x3c,
	0x5b, 0x8b, 0x80, 0xf2, 0x1a, 0x14, 0x89, 0x38, 0xad, 0x3b, 0x96, 0x32, 0x29, 0x4e, 0x95, 0xfa,
	0x5f, 0x96, 0x0a, 0xe1, 0x95, 0xcd, 0x7d, 0xad, 0x10, 0x86, 0x9b, 0x96, 0xac, 0x40, 0xde, 0x27,
	0xf8, 0xc8, 0xe9, 0x20, 0x65, 0x8a, 0x03, 0xb5, 0xc8, 0x94, 0xcb, 0x90, 0xef, 0xba, 0x3a, 0x3b,
	0xf5, 0x91, 0x92, 0x11, 0x91, 0x5c, 0xd7, 0x7d, 0x78, 0xea, 0x23, 0x79, 0x05, 0x4a, 0x94, 0x19,
	0xc7, 0x48, 0x37, 0x5c, 0x1c, 0x78, 0x4c, 0xc9, 0x2e, 0x4b, 0xab, 0x53, 0xda, 0xb4, 0xf0, 0xed,
	0x08, 0xd7, 0x76, 0xe9, 0xe5, 0xe5, 0xd9, 0x7a, 0x44, 0xa7, 0xbe, 0x0f, 0xe5, 0x91, 0xaa, 0x34,
	0x44, 0x7d, 0xec, 0x51, 0x34, 0xcc, 0x54, 0xfa, 0x11, 0xd3, 0xfa, 0xdb, 0x49, 0x98, 0x3d, 0xa0,
	0xf6, 0x61, 0xd0, 0x72, 0x1d, 0xb6, 0x6b, 0x30, 0xb3, 0x2d, 0xdf, 0x85, 0x22, 0x45, 0x27, 0x01,
	0xf2, 0x4c, 0x34, 0x5e, 0x9d, 0x2b, 0xe8, 0xaf, 0xe8, 0xb3, 0x04, 0xd3, 0x2d, 0x9e, 0x4b, 0x77,
	0x3c, 0x0b, 0xf5, 0x84, 0x46, 0x19, 0x0d, 0x84, 0xab, 0xc9, 0x3d, 0xf2, 0xbf, 0x00, 0x94, 0x19,
	0x0c, 0xe9, 0x04, 0x63, 0x26, 0x94, 0x2a, 0x69, 0x45, 0xe1, 0xd1, 0x30, 0x66, 0xf2, 0xff, 0x30,
	0xe7, 0x13, 0xd4, 0xd5, 0x13, 0x98, 0xac, 0xc0, 0xcc, 0x70, 0xf7, 0x61, 0x8c, 0xab, 0x40, 0x81,
	0xf5, 0x74, 0x53, 0x08, 0x9a, 0x13, 0x49, 0xf2, 0xac, 0xb7, 0xc7, 0x4d, 0x79, 0x11, 0x8a, 0x96,
	0xc1, 0x0c, 0xbd, 0x6d, 0xd0, 0xb6, 0x92, 0x17, 0x87, 0x0b, 0xdc, 0x71, 0xdf, 0xa0, 0x6d, 0x79,
	0x1e, 0xb2, 0x3e, 0xc1, 0xf8, 0x48, 0x29, 0x88, 0x40, 0x68, 0x6c, 0xcf, 0x72, 0xfd, 0xaf, 0x0a,
	0xae, 0x2b, 0xb0, 0x30, 0x2c, 0x5d, 0xf4, 0x02, 0xea, 0xef, 0x25, 0xf8, 0x9b, 0xbf, 0x9c, 0xb6,
	0xd1, 0xe9, 0x20, 0xcf, 0x46, 0xa1, 0xb0, 0xf7, 0x00, 0xcc, 0xc8, 0x33, 0x5e, 0xd9, 0x04, 0xf6,
	0xb7, 0x4a, 0x1b, 0xd7, 0x96, 0x49, 0xd6, 0x36, 0xc7, 0x6b, 0x4b, 0xa4, 0xac, 0x2f, 0x42, 0xe5,
	0xbb, 0x0a, 0xe2, 0xfa, 0x5e, 0x4b, 0xa2, 0x6b, 0x1e, 0x18, 0x01, 0xbd, 0xa1, 0x89, 0x5a, 0x80,
	0x1c, 0x41, 0x06, 0xc5, 0xde, 0x60, 0xa0, 0x06, 0xd6, 0xc8, 0x4c, 0x84, 0x6f, 0x24, 0x41, 0x2b,
	0x66, 0xfc, 0x5c, 0xec, 0x00, 0x0d, 0xd1, 0xc0, 0xbd, 0x19, 0xc6, 0x23, 0xcc, 0x2a, 0x62, 0x5a,
	0x93, 0xf9, 0x63, 0x6a, 0xcf, 0x60, 0x86, 0xb7, 0x11, 0xc3, 0xfe, 0x9f, 0x20, 0x56, 0x86, 0x7f,
	0x86, 0xb2, 0x47, 0xb4, 0xb6, 0xde, 0x65, 0x60, 0xea, 0x80, 0xda, 0xf2, 0x53, 0x28, 0x0d, 0xad,
	0xce, 0x95, 0xc6, 0xe8, 0xae, 0x6e, 0x8c, 0xec, 0xa1, 0xea, 0xda, 0x58, 0x48, 0xbc, 0xaa, 0x1e,
	0xc3, 0x74, 0x72, 0xf7, 0x2c, 0xa7, 0x9e, 0x4c, 0x20, 0xaa, 0xab, 0xe3, 0x10, 0xf1, 0xd5, 0x2d,
	0x98, 0x1d, 0x19, 0xc0, 0xff, 0xd2, 0x79, 0x0d, 0x81, 0xaa, 0xb7, 0x7f, 0x02, 0x94, 0xa4, 0x9f,
	0x1c, 0x82, 0x74, 0xfa, 0x09, 0xc4, 0x35, 0xf4, 0x53, 0x3a, 0x96, 0xeb, 0x3e, 0xd4, 0xae, 0xe9,
	0xba, 0x27, 0x21, 0xd7, 0xe8, 0x9e, 0xd6, 0x74, 0xf2, 0x23, 0x80, 0x44, 0xc7, 0x2d, 0xa5, 0x8b,
	0x1a, 0x03, 0xaa, 0xb7, 0xc6, 0x00, 0xa2, 0x7b, 0xab, 0xd9, 0x17, 0x97, 0x67, 0xeb, 0xd2, 0x6e,
	0xf3, 0x43, 0xbf, 0x26, 0x9d, 0xf7, 0x6b, 0xd2, 0xd7, 0x7e, 0x4d, 0x7a, 0x75, 0x51, 0x9b, 0x38,
	0xbf, 0xa8, 0x4d, 0x7c, 0xbe, 0xa8, 0x4d, 0x3c, 0x51, 0x6d, 0x87, 0xb5, 0x83, 0x56, 0xc3, 0xc4,
	0xae, 0x7a, 0xf5, 0x3f, 0x10, 0x3f, 0x6d, 0x98, 0x98, 0x20, 0xb5, 0x27, 0x7e, 0x10, 0xf8, 0x57,
	0x92, 0xb6, 0x72, 0xe2, 0x2b, 0x7e, 0xe7, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0x21, 0x97,
	0xba, 0x3e, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateRollup(ctx context.Context, in *MsgCreateRollup, opts ...grpc.CallOption) (*MsgCreateRollupResponse, error)
	SubmitBatch(ctx context.Context, in *MsgSubmitBatch, opts ...grpc.CallOption) (*MsgSubmitBatchResponse, error)
	ChallengeBatch(ctx context.Context, in *MsgChallengeBatch, opts ...grpc.CallOption) (*MsgChallengeBatchResponse, error)
	PauseRollup(ctx context.Context, in *MsgPauseRollup, opts ...grpc.CallOption) (*MsgPauseRollupResponse, error)
	ResumeRollup(ctx context.Context, in *MsgResumeRollup, opts ...grpc.CallOption) (*MsgResumeRollupResponse, error)
	StopRollup(ctx context.Context, in *MsgStopRollup, opts ...grpc.CallOption) (*MsgStopRollupResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateRollup(ctx context.Context, in *MsgCreateRollup, opts ...grpc.CallOption) (*MsgCreateRollupResponse, error) {
	out := new(MsgCreateRollupResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rdk.v1.Msg/CreateRollup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitBatch(ctx context.Context, in *MsgSubmitBatch, opts ...grpc.CallOption) (*MsgSubmitBatchResponse, error) {
	out := new(MsgSubmitBatchResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rdk.v1.Msg/SubmitBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChallengeBatch(ctx context.Context, in *MsgChallengeBatch, opts ...grpc.CallOption) (*MsgChallengeBatchResponse, error) {
	out := new(MsgChallengeBatchResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rdk.v1.Msg/ChallengeBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PauseRollup(ctx context.Context, in *MsgPauseRollup, opts ...grpc.CallOption) (*MsgPauseRollupResponse, error) {
	out := new(MsgPauseRollupResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rdk.v1.Msg/PauseRollup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResumeRollup(ctx context.Context, in *MsgResumeRollup, opts ...grpc.CallOption) (*MsgResumeRollupResponse, error) {
	out := new(MsgResumeRollupResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rdk.v1.Msg/ResumeRollup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) StopRollup(ctx context.Context, in *MsgStopRollup, opts ...grpc.CallOption) (*MsgStopRollupResponse, error) {
	out := new(MsgStopRollupResponse)
	err := c.cc.Invoke(ctx, "/qorechain.rdk.v1.Msg/StopRollup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateRollup(context.Context, *MsgCreateRollup) (*MsgCreateRollupResponse, error)
	SubmitBatch(context.Context, *MsgSubmitBatch) (*MsgSubmitBatchResponse, error)
	ChallengeBatch(context.Context, *MsgChallengeBatch) (*MsgChallengeBatchResponse, error)
	PauseRollup(context.Context, *MsgPauseRollup) (*MsgPauseRollupResponse, error)
	ResumeRollup(context.Context, *MsgResumeRollup) (*MsgResumeRollupResponse, error)
	StopRollup(context.Context, *MsgStopRollup) (*MsgStopRollupResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateRollup(ctx context.Context, req *MsgCreateRollup) (*MsgCreateRollupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRollup not implemented")
}
func (*UnimplementedMsgServer) SubmitBatch(ctx context.Context, req *MsgSubmitBatch) (*MsgSubmitBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (*UnimplementedMsgServer) ChallengeBatch(ctx context.Context, req *MsgChallengeBatch) (*MsgChallengeBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChallengeBatch not implemented")
}
func (*UnimplementedMsgServer) PauseRollup(ctx context.Context, req *MsgPauseRollup) (*MsgPauseRollupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseRollup not implemented")
}
func (*UnimplementedMsgServer) ResumeRollup(ctx context.Context, req *MsgResumeRollup) (*MsgResumeRollupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeRollup not implemented")
}
func (*UnimplementedMsgServer) StopRollup(ctx context.Context, req *MsgStopRollup) (*MsgStopRollupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopRollup not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateRollup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateRollup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateRollup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rdk.v1.Msg/CreateRollup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateRollup(ctx, req.(*MsgCreateRollup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rdk.v1.Msg/SubmitBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitBatch(ctx, req.(*MsgSubmitBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChallengeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChallengeBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChallengeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rdk.v1.Msg/ChallengeBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChallengeBatch(ctx, req.(*MsgChallengeBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PauseRollup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPauseRollup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PauseRollup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rdk.v1.Msg/PauseRollup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PauseRollup(ctx, req.(*MsgPauseRollup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResumeRollup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResumeRollup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResumeRollup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rdk.v1.Msg/ResumeRollup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResumeRollup(ctx, req.(*MsgResumeRollup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_StopRollup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStopRollup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StopRollup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.rdk.v1.Msg/StopRollup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StopRollup(ctx, req.(*MsgStopRollup))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.rdk.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRollup",
			Handler:    _Msg_CreateRollup_Handler,
		},
		{
			MethodName: "SubmitBatch",
			Handler:    _Msg_SubmitBatch_Handler,
		},
		{
			MethodName: "ChallengeBatch",
			Handler:    _Msg_ChallengeBatch_Handler,
		},
		{
			MethodName: "PauseRollup",
			Handler:    _Msg_PauseRollup_Handler,
		},
		{
			MethodName: "ResumeRollup",
			Handler:    _Msg_ResumeRollup_Handler,
		},
		{
			MethodName: "StopRollup",
			Handler:    _Msg_StopRollup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/rdk/v1/tx.proto",
}

func (m *MsgCreateRollup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRollup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRollup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StakeAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StakeAmount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.VmType) > 0 {
		i -= len(m.VmType)
		copy(dAtA[i:], m.VmType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VmType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Profile) > 0 {
		i -= len(m.Profile)
		copy(dAtA[i:], m.Profile)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Profile)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRollupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRollupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRollupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DataHash) > 0 {
		i -= len(m.DataHash)
		copy(dAtA[i:], m.DataHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DataHash)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TxCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TxCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PrevStateRoot) > 0 {
		i -= len(m.PrevStateRoot)
		copy(dAtA[i:], m.PrevStateRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrevStateRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.BatchIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BatchIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sequencer) > 0 {
		i -= len(m.Sequencer)
		copy(dAtA[i:], m.Sequencer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sequencer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgChallengeBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChallengeBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChallengeBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x22
	}
	if m.BatchIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BatchIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Challenger) > 0 {
		i -= len(m.Challenger)
		copy(dAtA[i:], m.Challenger)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Challenger)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChallengeBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChallengeBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChallengeBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPauseRollup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseRollup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseRollup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPauseRollupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseRollupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseRollupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgResumeRollup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResumeRollup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResumeRollup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgResumeRollupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResumeRollupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResumeRollupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgStopRollup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStopRollup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStopRollup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RollupID) > 0 {
		i -= len(m.RollupID)
		copy(dAtA[i:], m.RollupID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RollupID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStopRollupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStopRollupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStopRollupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateRollup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Profile)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VmType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StakeAmount != 0 {
		n += 1 + sovTx(uint64(m.StakeAmount))
	}
	return n
}

func (m *MsgCreateRollupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sequencer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BatchIndex != 0 {
		n += 1 + sovTx(uint64(m.BatchIndex))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PrevStateRoot)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TxCount != 0 {
		n += 1 + sovTx(uint64(m.TxCount))
	}
	l = len(m.DataHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgChallengeBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Challenger)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BatchIndex != 0 {
		n += 1 + sovTx(uint64(m.BatchIndex))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgChallengeBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPauseRollup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPauseRollupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgResumeRollup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgResumeRollupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgStopRollup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RollupID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStopRollupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateRollup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRollup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRollup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Profile", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Profile = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VmType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VmType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeAmount", wireType)
			}
			m.StakeAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakeAmount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRollupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRollupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRollupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchIndex", wireType)
			}
			m.BatchIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevStateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevStateRoot = append(m.PrevStateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevStateRoot == nil {
				m.PrevStateRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxCount", wireType)
			}
			m.TxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataHash = append(m.DataHash[:0], dAtA[iNdEx:postIndex]...)
			if m.DataHash == nil {
				m.DataHash = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChallengeBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChallengeBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChallengeBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenger = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchIndex", wireType)
			}
			m.BatchIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChallengeBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChallengeBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChallengeBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseRollup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseRollup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseRollup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseRollupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseRollupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseRollupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResumeRollup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResumeRollup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResumeRollup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResumeRollupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResumeRollupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResumeRollupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStopRollup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStopRollup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStopRollup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStopRollupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStopRollupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStopRollupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
